(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var p,q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function ba(){ba=function(){};q.Symbol||(q.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function da(){ba();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(this)}});da=function(){}}function ea(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){da();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ha(a){da();var b=a[Symbol.iterator];return b?b.call(a):ea(a)}
function ia(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(B)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!g(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=m(document,"link[rel=import]:not([import-dependency])"),
c=b.length;c?n(b,function(b){return h(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function h(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);ua&&"style"===a.localName||a.addEventListener("error",c)}}function g(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.a={};this.b=0;this.c=new MutationObserver(function(b){return a.wa(b)});this.c.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a){n(m(a,"template"),function(a){n(m(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"]'),
function(a){var b=document.createElement("script");n(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});l(a.content)})}function m(a,b){return a.childNodes.length?a.querySelectorAll(b):Uc}function n(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var t=document.createElement("link"),B="import"in t,Uc=t.querySelectorAll("*"),va=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",
{get:function(){return va||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Vc=/(url\()([^)]*)(\))/g,Wc=/(@import[\s]+(?!url\())([^;]*)(;)/g,Xc=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,x={qa:function(a,b){a.href&&a.setAttribute("href",x.L(a.getAttribute("href"),b));a.src&&a.setAttribute("src",x.L(a.getAttribute("src"),b));if("style"===a.localName){var c=x.aa(a.textContent,b,Vc);a.textContent=x.aa(c,b,Wc)}},aa:function(a,b,c){return a.replace(c,
function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=x.L(a,b));return c+"'"+a+"'"+e})},L:function(a,b){if(void 0===x.P){x.P=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";x.P="http://a/c%20d"===c.href}catch(se){}}if(x.P)return(new URL(a,b)).href;c=x.ha;c||(c=document.implementation.createHTMLDocument("temp"),x.ha=c,c.W=c.createElement("base"),c.head.appendChild(c.W),c.V=c.createElement("a"));c.W.href=b;c.V.href=a;return c.V.href||a}},kb={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=
a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,kb.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},ua=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);
k.prototype.loadImports=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){return b.u(a)})};k.prototype.u=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.__import=d,this.h(a))}else this.b++,this.a[c]="pending",kb.load(c,function(a,d){a=b.xa(a,d||c);b.a[c]=a;b.b--;b.loadImports(a);b.B()},function(){b.a[c]=null;b.b--;b.B()})};k.prototype.xa=function(a,b){if(!a)return document.createDocumentFragment();ua&&(a=a.replace(Xc,function(a,b,c){return-1===
a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,l(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=x.L(c.getAttribute("href"),b),c.removeAttribute("href");c=m(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"]');
var d=0;n(c,function(a){h(a);x.qa(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};k.prototype.B=function(){var a=this;if(!this.b){this.c.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.loadImports(document),a.b||(a.c.observe(document.head,{childList:!0,subtree:!0}),
a.ua()))};this.za(function(){c=!0;d()});this.ya(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){var c=b.a[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),a.appendChild(c))})};k.prototype.ya=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");n(f.attributes,function(a){return g.setAttribute(a.name,
a.value)});va=g;f.parentNode.replaceChild(g,f);h(g,function(){va=null;b(e+1)})}else a()}var c=m(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.za=function(a){var b=m(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=ua&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");n(b,function(b){h(b,function(){b.removeAttribute("import-dependency");0===--d&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);
f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.ua=function(){var a=this,b=m(document,"link[rel=import]");n(b,function(b){return a.h(b)},!0)};k.prototype.h=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,
cancelable:!1,detail:void 0})))};k.prototype.wa=function(a){var b=this;n(a,function(a){return n(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(g(a)?b.u(a):b.loadImports(a))})})};var wa=null;if(B)t=m(document,"link[rel=import]"),n(t,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),t=function(a){a=a.target;g(a)&&(a.__loaded=!0)},document.addEventListener("load",t,!0),document.addEventListener("error",t,!0);else{var S=Object.getOwnPropertyDescriptor(Node.prototype,
"baseURI");Object.defineProperty((!S||S.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=g(this)?this:c(this);return a?a.href:S&&S.get?S.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){wa=new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,
detail:void 0}))});a.useNative=B;a.whenReady=f;a.importForElement=c;a.loadImports=function(a){wa&&wa.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var r=window.ShadyDOM||{};r.sa=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ja=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");r.C=!!(ja&&ja.configurable&&ja.get);r.$=r.force||!r.sa;function u(a){return a.__shady&&void 0!==a.__shady.firstChild}function v(a){return"ShadyRoot"===a.ea}function w(a){a=a.getRootNode();if(v(a))return a}var y=Element.prototype,ka=y.matches||y.matchesSelector||y.mozMatchesSelector||y.msMatchesSelector||y.oMatchesSelector||y.webkitMatchesSelector;
function la(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function ma(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)la(a,c[d]);return a}function na(a,b){for(var c in b)a[c]=b[c]}var oa=document.createTextNode(""),pa=0,qa=[];(new MutationObserver(function(){for(;qa.length;)try{qa.shift()()}catch(a){throw oa.textContent=pa++,a;}})).observe(oa,{characterData:!0});
function ra(a){qa.push(a);oa.textContent=pa++}var sa=!!document.contains;function ta(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1};var z=[],xa;function ya(a){xa||(xa=!0,ra(za));z.push(a)}function za(){xa=!1;for(var a=!!z.length;z.length;)z.shift()();return a}za.list=z;function Aa(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.J=new Set}function Ba(a){a.a||(a.a=!0,ra(function(){Ca(a)}))}function Ca(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.J.forEach(function(a){a(b)})}}Aa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Da(a,b){a.__shady=a.__shady||{};a.__shady.D||(a.__shady.D=new Aa);a.__shady.D.J.add(b);var c=a.__shady.D;return{ia:b,la:c,ka:a,takeRecords:function(){return c.takeRecords()}}}function Ea(a){var b=a&&a.la;b&&(b.J.delete(a.ia),b.J.size||(a.ka.__shady.D=null))}
function Fa(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var A={},Ga=Element.prototype.insertBefore,Ha=Element.prototype.removeChild,Ia=Element.prototype.setAttribute,Ja=Element.prototype.removeAttribute,Ka=Element.prototype.cloneNode,La=Document.prototype.importNode,Ma=Element.prototype.addEventListener,Na=Element.prototype.removeEventListener,Oa=Window.prototype.addEventListener,Pa=Window.prototype.removeEventListener,Qa=Element.prototype.dispatchEvent,Ra=Element.prototype.querySelector,Sa=Element.prototype.querySelectorAll,Ta=Node.prototype.contains||
HTMLElement.prototype.contains;A.appendChild=Element.prototype.appendChild;A.insertBefore=Ga;A.removeChild=Ha;A.setAttribute=Ia;A.removeAttribute=Ja;A.cloneNode=Ka;A.importNode=La;A.addEventListener=Ma;A.removeEventListener=Na;A.Fa=Oa;A.Ga=Pa;A.dispatchEvent=Qa;A.querySelector=Ra;A.querySelectorAll=Sa;A.contains=Ta;var Ua=/[&\u00A0"]/g,Va=/[&\u00A0<>]/g;function Wa(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Xa(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ya=Xa("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Za=Xa("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function $a(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,h;e<f&&(h=d[e]);e++){a:{var g=h;var k=a;var l=b;switch(g.nodeType){case Node.ELEMENT_NODE:for(var m=g.localName,n="<"+m,t=g.attributes,B=0;k=t[B];B++)n+=" "+k.name+'="'+k.value.replace(Ua,Wa)+'"';n+=">";g=Ya[m]?n:n+$a(g,l)+"</"+m+">";break a;case Node.TEXT_NODE:g=g.data;g=k&&Za[k.localName]?g:g.replace(Va,Wa);break a;case Node.COMMENT_NODE:g="\x3c!--"+g.data+"--\x3e";break a;default:throw window.console.error(g),
Error("not implemented");}}c+=g}return c};var C={},D=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),E=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function ab(a){var b=[];D.currentNode=a;for(a=D.firstChild();a;)b.push(a),a=D.nextSibling();return b}C.parentNode=function(a){D.currentNode=a;return D.parentNode()};C.firstChild=function(a){D.currentNode=a;return D.firstChild()};C.lastChild=function(a){D.currentNode=a;return D.lastChild()};C.previousSibling=function(a){D.currentNode=a;return D.previousSibling()};
C.nextSibling=function(a){D.currentNode=a;return D.nextSibling()};C.childNodes=ab;C.parentElement=function(a){E.currentNode=a;return E.parentNode()};C.firstElementChild=function(a){E.currentNode=a;return E.firstChild()};C.lastElementChild=function(a){E.currentNode=a;return E.lastChild()};C.previousElementSibling=function(a){E.currentNode=a;return E.previousSibling()};C.nextElementSibling=function(a){E.currentNode=a;return E.nextSibling()};
C.children=function(a){var b=[];E.currentNode=a;for(a=E.firstChild();a;)b.push(a),a=E.nextSibling();return b};C.innerHTML=function(a){return $a(a,function(a){return ab(a)})};C.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var bb=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),cb=document.implementation.createHTMLDocument("inert"),db=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),eb={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentNode;a&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:C.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;
return void 0!==a?a:C.parentNode(this)},configurable:!0},nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:C.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;return void 0!==a?a:C.previousSibling(this)},configurable:!0},className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&
void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return C.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return C.previousElementSibling(this)},configurable:!0}},fb={childNodes:{get:function(){if(u(this)){if(!this.__shady.childNodes){this.__shady.childNodes=
[];for(var a=this.firstChild;a;a=a.nextSibling)this.__shady.childNodes.push(a)}var b=this.__shady.childNodes}else b=C.childNodes(this);b.item=function(a){return b[a]};return b},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=this.__shady&&this.__shady.firstChild;return void 0!==a?a:C.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;return void 0!==a?a:C.lastChild(this)},
configurable:!0},textContent:{get:function(){if(u(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return C.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(;this.firstChild;)this.removeChild(this.firstChild);(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=
a}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return C.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return C.lastElementChild(this)},configurable:!0},children:{get:function(){var a=u(this)?
Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE}):C.children(this);a.item=function(b){return a[b]};return a},configurable:!0},innerHTML:{get:function(){var a="template"===this.localName?this.content:this;return u(this)?$a(a):C.innerHTML(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);var c=this.localName;c&&"template"!==c||(c="div");c=cb.createElement(c);for(bb&&bb.set?bb.set.call(c,
a):c.innerHTML=a;c.firstChild;)b.appendChild(c.firstChild)},configurable:!0}},gb={shadowRoot:{get:function(){return this.__shady&&this.__shady.Aa||null},configurable:!0}},hb={activeElement:{get:function(){var a=db&&db.get?db.get.call(document):r.C?void 0:document.activeElement;if(a&&a.nodeType){var b=!!v(this);if(this===document||b&&this.host!==a&&A.contains.call(this.host,a)){for(b=w(a);b&&b!==this;)a=b.host,b=w(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},
configurable:!0}};function F(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function G(a){F(a,eb);F(a,fb);F(a,hb)}var ib=r.C?function(){}:function(a){a.__shady&&a.__shady.fa||(a.__shady=a.__shady||{},a.__shady.fa=!0,F(a,eb,!0))},jb=r.C?function(){}:function(a){a.__shady&&a.__shady.da||(a.__shady=a.__shady||{},a.__shady.da=!0,F(a,fb,!0),F(a,gb,!0))};function lb(a,b,c){ib(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&(b.__shady.firstChild=a):(b.__shady.lastChild=a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}
function mb(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=C.firstChild(a);a.__shady.lastChild=C.lastChild(a);jb(a);for(var b=a.__shady.childNodes=C.childNodes(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,ib(d)}};function nb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==d&&d!==a||void 0===d&&C.parentNode(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&ob(b.parentNode,b);d=w(a);var e;if(e=d)a:{if(!b.__noInsertionPoint){var f;"slot"===b.localName?f=[b]:
b.querySelectorAll&&(f=b.querySelectorAll("slot"));if(f&&f.length){e=f;break a}}e=void 0}(f=e)&&d.w.push.apply(d.w,[].concat(f instanceof Array?f:ia(ha(f))));d&&("slot"===a.localName||f)&&H(d);if(u(a)){d=c;jb(a);a.__shady=a.__shady||{};void 0!==a.__shady.firstChild&&(a.__shady.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(e=0;e<f.length;e++)lb(f[e],a,d);b.__shady=b.__shady||{};d=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=b.__shady.lastChild=d;
b.__shady.childNodes=d}else lb(b,a,d);if(pb(a)){H(a.__shady.root);var h=!0}else a.__shady.root&&(h=!0)}h||(h=v(a)?a.host:a,c?(c=qb(c),A.insertBefore.call(h,b,c)):A.appendChild.call(h,b));rb(a,b);return b}
function ob(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=w(b);if(u(a)){b.__shady=b.__shady||{};a.__shady=a.__shady||{};b===a.__shady.firstChild&&(a.__shady.firstChild=b.__shady.nextSibling);b===a.__shady.lastChild&&(a.__shady.lastChild=b.__shady.previousSibling);var d=b.__shady.previousSibling,e=b.__shady.nextSibling;d&&(d.__shady=d.__shady||{},d.__shady.nextSibling=e);e&&(e.__shady=e.__shady||{},e.__shady.previousSibling=d);b.__shady.parentNode=
b.__shady.previousSibling=b.__shady.nextSibling=void 0;void 0!==a.__shady.childNodes&&(a.__shady.childNodes=null);if(pb(a)){H(a.__shady.root);var f=!0}}sb(b);if(c){(d=a&&"slot"===a.localName)&&(f=!0);tb(c);e=c.g;for(var h in e)for(var g=e[h],k=0;k<g.length;k++){var l=g[k];if(ta(b,l)){g.splice(k,1);var m=c.j.indexOf(l);0<=m&&c.j.splice(m,1);k--;if(m=l.__shady.A)for(l=0;l<m.length;l++){var n=m[l],t=C.parentNode(n);t&&A.removeChild.call(t,n)}m=!0}}(m||d)&&H(c)}f||(f=v(a)?a.host:a,(!a.__shady.root&&"slot"!==
b.localName||f===C.parentNode(b))&&A.removeChild.call(f,b));rb(a,null,b);return b}function sb(a){if(a.__shady&&void 0!==a.__shady.U)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)sb(e);a.__shady&&(a.__shady.U=void 0)}function qb(a){var b=a;a&&"slot"===a.localName&&(b=(b=a.__shady&&a.__shady.A)&&b.length?b[0]:qb(a.nextSibling));return b}function pb(a){return(a=a&&a.__shady&&a.__shady.root)&&ub(a)}
function vb(a,b){if("slot"===b)a=a.parentNode,pb(a)&&H(a.__shady.root);else if("slot"===a.localName&&"name"===b&&(b=w(a))){var c=a.ga,d=wb(a);if(d!==c){c=b.g[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.g[d]||(b.g[d]=[]);c.push(a);1<c.length&&(b.g[d]=xb(c))}H(b)}}function rb(a,b,c){if(a=a.__shady&&a.__shady.D)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ba(a)}
function yb(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.U;void 0===b&&(b=v(a)?a:(b=a.parentNode)?yb(b):a,A.contains.call(document.documentElement,a)&&(a.__shady.U=b));return b}}function zb(a,b,c){var d=[];Ab(a.childNodes,b,c,d);return d}function Ab(a,b,c,d){for(var e=0,f=a.length,h;e<f&&(h=a[e]);e++){var g;if(g=h.nodeType===Node.ELEMENT_NODE){g=h;var k=b,l=c,m=d,n=k(g);n&&m.push(g);l&&l(n)?g=n:(Ab(g.childNodes,k,l,m),g=void 0)}if(g)break}}var Bb=null;
function Cb(a,b,c){Bb||(Bb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);Bb&&"class"===b?Bb.setElementClass(a,c):(A.setAttribute.call(a,b,c),vb(a,b))}function Db(a,b){if(a.ownerDocument!==document)return A.importNode.call(document,a,b);var c=A.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Db(a[b],!0),c.appendChild(d)}return c};var I="__eventWrappers"+Date.now(),Eb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,
dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0};function Fb(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}
function Gb(a,b){if(!v)return a;a=Fb(a,!0);for(var c=0,d,e,f,h;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(h=a.indexOf(f),e=f),!v(f)||-1<h)return d}
var Hb={get composed(){!1!==this.isTrusted&&void 0===this.M&&(this.M=Eb[this.type]);return this.M||!1},composedPath:function(){this.b||(this.b=Fb(this.__target,this.composed));return this.b},get target(){return Gb(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.N)return null;this.c||(this.c=Fb(this.N,!0));return Gb(this.currentTarget,this.c)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.a=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
this.a=this.h=!0}};function Ib(a){function b(b,d){b=new a(b,d);b.M=d&&!!d.composed;return b}na(b,a);b.prototype=a.prototype;return b}var Jb={focus:!0,blur:!0};function Kb(a){return a.__target!==a.target||a.N!==a.relatedTarget}function Lb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!Kb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.h);d++);}
function Mb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];Lb(a,d,"capture");if(a.a)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=d.__shady&&d.__shady.root;if(0===c||f&&f===e)if(Lb(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.a)break}}
function Nb(a,b,c,d,e,f){for(var h=0;h<a.length;h++){var g=a[h],k=g.type,l=g.capture,m=g.once,n=g.passive;if(b===g.node&&c===k&&d===l&&e===m&&f===n)return h}return-1}
function Ob(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var h=!!c.passive}else e=!!c,h=f=!1;var g=c&&c.O||this,k=b[I];if(k){if(-1<Nb(k,g,a,e,f,h))return}else b[I]=[];k=function(e){f&&this.removeEventListener(a,b,c);e.__target||Pb(e);if(g!==this){var h=Object.getOwnPropertyDescriptor(e,"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return g},
configurable:!0})}if(e.composed||-1<e.composedPath().indexOf(g))if(Kb(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===g||g instanceof Window){var k="function"===d?b.call(g,e):b.handleEvent&&b.handleEvent(e);g!==this&&(h?(Object.defineProperty(e,"currentTarget",h),h=null):delete e.currentTarget);return k}};b[I].push({node:this,type:a,capture:e,once:f,passive:h,Ha:k});Jb[a]?(this.__handlers=
this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(k)):(this instanceof Window?A.Fa:A.addEventListener).call(this,a,k,c)}}}
function Qb(a,b,c){if(b){if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var h=c&&c.O||this,g=void 0;var k=null;try{k=b[I]}catch(l){}k&&(e=Nb(k,h,a,d,e,f),-1<e&&(g=k.splice(e,1)[0].Ha,k.length||(b[I]=void 0)));(this instanceof Window?A.Ga:A.removeEventListener).call(this,a,g||b,c);g&&Jb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],g=a.indexOf(g),-1<g&&a.splice(g,1))}}
function Rb(){for(var a in Jb)window.addEventListener(a,function(a){a.__target||(Pb(a),Mb(a))},!0)}function Pb(a){a.__target=a.target;a.N=a.relatedTarget;if(r.C){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Ja=b;la(c,Hb);b.__patchProto=c}a.__proto__=b.__patchProto}else la(a,Hb)}var Sb=Ib(window.Event),Tb=Ib(window.CustomEvent),Ub=Ib(window.MouseEvent);function J(a,b){return{index:a,F:[],I:b}}
function Vb(a,b,c,d){var e=0,f=0,h=0,g=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(h=0;h<k;h++)if(a[h]!==c[h])break a;h=k}if(b==a.length&&d==c.length){g=a.length;for(var l=c.length,m=0;m<k-h&&Wb(a[--g],c[--l]);)m++;g=m}e+=h;f+=h;b-=g;d-=g;if(0==b-e&&0==d-f)return[];if(e==b){for(b=J(e,0);f<d;)b.F.push(c[f++]);return[b]}if(f==d)return[J(e,b-e)];k=e;h=f;d=d-h+1;g=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(g),b[l][0]=l;for(l=0;l<g;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<g;m++)if(a[k+m-1]===c[h+l-1])b[l][m]=
b[l-1][m-1];else{var n=b[l-1][m]+1,t=b[l][m-1]+1;b[l][m]=n<t?n:t}k=b.length-1;h=b[0].length-1;d=b[k][h];for(a=[];0<k||0<h;)0==k?(a.push(2),h--):0==h?(a.push(3),k--):(g=b[k-1][h-1],l=b[k-1][h],m=b[k][h-1],n=l<m?l<g?l:g:m<g?m:g,n==g?(g==d?a.push(0):(a.push(1),d=g),k--,h--):n==l?(a.push(3),k--,d=l):(a.push(2),h--,d=m));a.reverse();b=void 0;k=[];for(h=0;h<a.length;h++)switch(a[h]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=J(e,0));b.I++;e++;b.F.push(c[f]);f++;break;case 2:b||(b=J(e,0));
b.I++;e++;break;case 3:b||(b=J(e,0)),b.F.push(c[f]),f++}b&&k.push(b);return k}function Wb(a,b){return a===b};var Xb={};function K(a,b,c){if(a!==Xb)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=K.prototype;a.ea="ShadyRoot";mb(b);mb(a);a.host=b;a.ja=c&&c.mode;b.__shady=b.__shady||{};b.__shady.root=a;b.__shady.Aa="closed"!==a.ja?a:null;a.H=!1;a.j=[];a.g={};a.w=[];c=C.childNodes(b);for(var d=0,e=c.length;d<e;d++)A.removeChild.call(b,c[d]);return a}K.prototype=Object.create(DocumentFragment.prototype);function H(a){a.H||(a.H=!0,ya(function(){return Yb(a)}))}
function Yb(a){for(var b;a;){a.H&&(b=a);a:{var c=a;a=c.host.getRootNode();if(v(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
K.prototype._renderRoot=function(){this.H=!1;tb(this);for(var a=0,b;a<this.j.length;a++){b=this.j[a];var c=b.__shady.assignedNodes;b.__shady.assignedNodes=[];b.__shady.A=[];if(b.__shady.X=c)for(var d=0;d<c.length;d++){var e=c[d];e.__shady.R=e.__shady.assignedSlot;e.__shady.assignedSlot===b&&(e.__shady.assignedSlot=null)}}for(b=this.host.firstChild;b;b=b.nextSibling)Zb(this,b);for(a=0;a<this.j.length;a++){b=this.j[a];if(!b.__shady.assignedNodes.length)for(c=b.firstChild;c;c=c.nextSibling)Zb(this,c,
b);c=b.parentNode;(c=c.__shady&&c.__shady.root)&&ub(c)&&c._renderRoot();$b(this,b.__shady.A,b.__shady.assignedNodes);if(c=b.__shady.X){for(d=0;d<c.length;d++)c[d].__shady.R=null;b.__shady.X=null;c.length>b.__shady.assignedNodes.length&&(b.__shady.S=!0)}b.__shady.S&&(b.__shady.S=!1,ac(this,b))}a=this.j;b=[];for(c=0;c<a.length;c++)d=a[c].parentNode,d.__shady&&d.__shady.root||!(0>b.indexOf(d))||b.push(d);for(a=0;a<b.length;a++){c=b[a];d=c===this?this.host:c;e=[];c=c.childNodes;for(var f=0;f<c.length;f++){var h=
c[f];if("slot"==h.localName){h=h.__shady.A;for(var g=0;g<h.length;g++)e.push(h[g])}else e.push(h)}c=void 0;f=C.childNodes(d);h=Vb(e,e.length,f,f.length);for(var k=g=0;g<h.length&&(c=h[g]);g++){for(var l=0,m;l<c.F.length&&(m=c.F[l]);l++)C.parentNode(m)===d&&A.removeChild.call(d,m),f.splice(c.index+k,1);k-=c.I}for(k=0;k<h.length&&(c=h[k]);k++)for(g=f[c.index],l=c.index;l<c.index+c.I;l++)m=e[l],A.insertBefore.call(d,m,g),f.splice(l,0,m)}};
function Zb(a,b,c){b.__shady=b.__shady||{};var d=b.__shady.R;b.__shady.R=null;c||(c=(a=a.g[b.slot||"__catchall"])&&a[0]);c?(c.__shady.assignedNodes.push(b),b.__shady.assignedSlot=c):b.__shady.assignedSlot=void 0;d!==b.__shady.assignedSlot&&b.__shady.assignedSlot&&(b.__shady.assignedSlot.__shady.S=!0)}function $b(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=e.__shady.assignedNodes;f&&f.length&&$b(a,b,f)}else b.push(c[d])}
function ac(a,b){A.dispatchEvent.call(b,new Event("slotchange"));b.__shady.assignedSlot&&ac(a,b.__shady.assignedSlot)}function tb(a){if(a.w.length){for(var b=a.w,c,d=0;d<b.length;d++){var e=b[d];e.__shady=e.__shady||{};mb(e);mb(e.parentNode);var f=wb(e);a.g[f]?(c=c||{},c[f]=!0,a.g[f].push(e)):a.g[f]=[e];a.j.push(e)}if(c)for(var h in c)a.g[h]=xb(a.g[h]);a.w=[]}}function wb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ga=b}
function xb(a){return a.sort(function(a,c){a=bc(a);for(var b=bc(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}function bc(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}function ub(a){tb(a);return!!a.j.length}K.prototype.addEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.O=this;this.host.addEventListener(a,b,c)};
K.prototype.removeEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.O=this;this.host.removeEventListener(a,b,c)};K.prototype.getElementById=function(a){return zb(this,function(b){return b.id==a},function(a){return!!a})[0]||null};var cc=K.prototype;F(cc,fb,!0);F(cc,hb,!0);function dc(a){var b=a.getRootNode();v(b)&&Yb(b);return a.__shady&&a.__shady.assignedSlot||null}
var ec={addEventListener:Ob.bind(window),removeEventListener:Qb.bind(window)},fc={addEventListener:Ob,removeEventListener:Qb,appendChild:function(a){return nb(this,a)},insertBefore:function(a,b){return nb(this,a,b)},removeChild:function(a){return ob(this,a)},replaceChild:function(a,b){nb(this,a,b);ob(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=A.cloneNode.call(this,a);else if(b=A.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return yb(this)},contains:function(a){return ta(this,a)},get isConnected(){var a=this.ownerDocument;if(sa&&A.contains.call(a,this)||a.documentElement&&A.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(a instanceof K?a.host:void 0);return!!(a&&a instanceof Document)},dispatchEvent:function(a){za();return A.dispatchEvent.call(this,a)}},gc={get assignedSlot(){return dc(this)}},
hc={querySelector:function(a){return zb(this,function(b){return ka.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a){return zb(this,function(b){return ka.call(b,a)})}},ic={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();v(b)&&Yb(b);return this.__shady?(a&&a.flatten?this.__shady.A:this.__shady.assignedNodes)||[]:[]}}},jc=ma({setAttribute:function(a,b){Cb(this,a,b)},removeAttribute:function(a){A.removeAttribute.call(this,a);vb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";
if(!a)throw"Not enough arguments.";return new K(Xb,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Cb(this,"slot",a)},get assignedSlot(){return dc(this)}},hc,ic);Object.defineProperties(jc,gb);var kc=ma({importNode:function(a,b){return Db(a,b)},getElementById:function(a){return zb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},hc);Object.defineProperties(kc,{_activeElement:hb.activeElement});
var lc=HTMLElement.prototype.blur,mc=ma({blur:function(){var a=this.__shady&&this.__shady.root;(a=a&&a.activeElement)?a.blur():lc.call(this)}});function L(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(r.$){var ShadyDOM={inUse:r.$,patch:function(a){return a},isShadyRoot:v,enqueue:ya,flush:za,settings:r,filterMutations:Fa,observeChildren:Da,unobserveChildren:Ea,nativeMethods:A,nativeTree:C};window.ShadyDOM=ShadyDOM;window.Event=Sb;window.CustomEvent=Tb;window.MouseEvent=Ub;Rb();var nc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;L(window.Node.prototype,fc);L(window.Window.prototype,ec);L(window.Text.prototype,gc);L(window.DocumentFragment.prototype,hc);L(window.Element.prototype,
jc);L(window.Document.prototype,kc);window.HTMLSlotElement&&L(window.HTMLSlotElement.prototype,ic);L(nc.prototype,mc);r.C&&(G(window.Node.prototype),G(window.Text.prototype),G(window.DocumentFragment.prototype),G(window.Element.prototype),G(nc.prototype),G(window.Document.prototype),window.HTMLSlotElement&&G(window.HTMLSlotElement.prototype));window.ShadowRoot=K};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function oc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function pc(a){a=a.replace(qc,"").replace(rc,"");var b=sc,c=a,d=new oc;d.start=0;d.end=c.length;for(var e=d,f=0,h=c.length;f<h;f++)if("{"===c[f]){e.rules||(e.rules=[]);var g=e,k=g.rules[g.rules.length-1]||null;e=new oc;e.start=f+1;e.parent=g;e.previous=k;g.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function sc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=tc(c),c=c.replace(uc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=vc:c.match(wc)&&(a.type=xc,a.keyframesName=a.selector.split(uc).pop()):a.type=0===c.indexOf("--")?yc:zc);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)sc(f,
b);return a}function tc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function Ac(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var h=e.length,g;f<h&&(g=e[f]);f++)d=Ac(g,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(Bc,"").replace(Cc,""),b=b.replace(Dc,"").replace(Ec,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var zc=1,xc=7,vc=4,yc=1E3,qc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,rc=/@import[^;]*;/gim,Bc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Cc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Dc=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Ec=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,wc=/^@[^\s]*keyframes/,uc=/\s+/g;var M=!(window.ShadyDOM&&window.ShadyDOM.inUse),Fc;function Gc(a){Fc=a&&a.shimcssproperties?!1:M||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?Fc=window.ShadyCSS.nativeCss:window.ShadyCSS?(Gc(window.ShadyCSS),window.ShadyCSS=void 0):Gc(window.WebComponents&&window.WebComponents.flags);var N=Fc;var Hc=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Ic=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Jc=/(--[\w-]+)\s*([:,;)]|$)/gi,Kc=/(animation\s*:)|(animation-name\s*:)/,Lc=/@media\s(.*)/,Mc=/\{[^}]*\}/g;var Nc=new Set;function O(a,b){if(!a)return"";"string"===typeof a&&(a=pc(a));b&&P(a,b);return Ac(a,N)}function Oc(a){!a.__cssRules&&a.textContent&&(a.__cssRules=pc(a.textContent));return a.__cssRules||null}function Pc(a){return!!a.parent&&a.parent.type===xc}function P(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===vc){var h=a.selector.match(Lc);h&&(window.matchMedia(h[1]).matches||(e=!0))}f===zc?b(a):c&&f===xc?c(a):f===yc&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var g;e<f&&(g=a[e]);e++)P(g,b,c,d)}}}
function Qc(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Rc(e,c,d);return e}var Q=null;function Rc(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);Q?a.compareDocumentPosition(Q)===Node.DOCUMENT_POSITION_PRECEDING&&(Q=a):Q=a}
function Sc(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=Sc(a.substring(e+1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function Tc(a,b){M?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function R(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,G:c}};function Yc(){}function Zc(a,b,c){var d=T;a.__styleScoped?a.__styleScoped=null:$c(d,a,b||"",c)}function $c(a,b,c,d){b.nodeType===Node.ELEMENT_NODE&&ad(b,c,d);if(b="template"===b.localName?(b.content||b.Ka).childNodes:b.children||b.childNodes)for(var e=0;e<b.length;e++)$c(a,b[e],c,d)}
function ad(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(bd);c?d&&(b=d.replace("style-scope","").replace(b,""),Tc(a,b)):Tc(a,(d?d+" ":"")+"style-scope "+b)}}function cd(a,b,c){var d=T,e=a.__cssBuild;M||"shady"===e?b=O(b,c):(a=R(a),b=dd(d,b,a.is,a.G,c)+"\n\n");return b.trim()}
function dd(a,b,c,d,e){var f=ed(c,d);c=c?fd+c:"";return O(b,function(b){b.c||(b.selector=b.i=gd(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function ed(a,b){return b?"[is="+a+"]":a}function gd(a,b,c,d,e){var f=b.selector.split(hd);if(!Pc(b)){b=0;for(var h=f.length,g;b<h&&(g=f[b]);b++)f[b]=c.call(a,g,d,e)}return f.join(hd)}function id(a){return a.replace(jd,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
Yc.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=jd.test(a);e&&(a=a.replace(jd,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=id(a));a=a.replace(kd,ld+" $1");a=a.replace(md,function(a,e,g){d||(a=nd(g,e,b,c),d=d||a.stop,e=a.pa,g=a.value);return e+g});e&&(a=id(a));return a};
function nd(a,b,c,d){var e=a.indexOf(od);0<=a.indexOf(ld)?a=pd(a,d):0!==e&&(a=c?qd(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(rd,function(a,b){return" > "+b}))}a=a.replace(sd,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,pa:b,stop:f}}function qd(a,b){a=a.split(td);a[0]+=b;return a.join(td)}
function pd(a,b){var c=a.match(ud);return(c=c&&c[2].trim()||"")?c[0].match(vd)?a.replace(ud,function(a,c,f){return b+f}):c.split(vd)[0]===b?c:wd:a.replace(ld,b)}function xd(a){a.selector===yd&&(a.selector="html")}Yc.prototype.c=function(a){return a.match(od)?this.b(a,zd):qd(a.trim(),zd)};q.Object.defineProperties(Yc.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var jd=/:(nth[-\w]+)\(([^)]+)\)/,zd=":not(.style-scope)",hd=",",md=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,vd=/[[.:#*]/,ld=":host",yd=":root",od="::slotted",kd=new RegExp("^("+od+")"),ud=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,rd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,sd=/(.*):dir\((?:(ltr|rtl))\)/,fd=".",td=":",bd="class",wd="should_not_match",T=new Yc;function U(a,b,c,d){this.o=a||null;this.b=b||null;this.T=c||[];this.v=null;this.G=d||"";this.a=this.l=this.s=null}function V(a){return a?a.__styleInfo:null}function Ad(a,b){return a.__styleInfo=b}U.prototype.c=function(){return this.o};U.prototype._getStyleRules=U.prototype.c;function Bd(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Cd=navigator.userAgent.match("Trident");function Dd(){}function Ed(a){var b={},c=[],d=0;P(a,function(a){Fd(a);a.index=d++;a=a.f.cssText;for(var c;c=Jc.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function Fd(a){if(!a.f){var b={},c={};Gd(a,c)&&(b.m=c,a.rules=null);b.cssText=a.parsedCssText.replace(Mc,"").replace(Hc,"");a.f=b}}function Gd(a,b){var c=a.f;if(c){if(c.m)return Object.assign(b,c.m),!0}else{c=a.parsedCssText;for(var d;a=Hc.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function W(a,b,c){b&&(b=0<=b.indexOf(";")?Hd(a,b,c):Sc(b,function(b,e,f,h){if(!e)return b+h;(e=W(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=W(a,c[f]||f,c)||f;return b+(e||"")+h}));return b&&b.trim()||""}
function Hd(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){Ic.lastIndex=0;if(f=Ic.exec(e))e=W(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var h=e.substring(f);h=h.trim();h=W(a,h,c)||h;e=e.substring(0,f)+h}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Id(a,b){var c={},d=[];P(a,function(a){a.f||Fd(a);var e=a.i||a.parsedSelector;b&&a.f.m&&e&&Bd.call(b,e)&&(Gd(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{m:c,key:d}}
function Jd(a,b,c,d){b.f||Fd(b);if(b.f.m){var e=R(a);a=e.is;e=e.G;e=a?ed(a,e):"html";var f=b.parsedSelector,h=":host > *"===f||"html"===f,g=0===f.indexOf(":host")&&!h;"shady"===c&&(h=f===e+" > *."+e||-1!==f.indexOf("html"),g=!h&&0===f.indexOf(e));"shadow"===c&&(h=":host > *"===f||"html"===f,g=g&&!h);if(h||g)c=e,g&&(b.i||(b.i=gd(T,b,T.b,a?fd+a:"",e)),c=b.i||e),d({Ca:c,va:g,La:h})}}
function Kd(a,b){var c={},d={},e=b&&b.__cssBuild;P(b,function(b){Jd(a,b,e,function(e){Bd.call(a.h||a,e.Ca)&&(e.va?Gd(b,c):Gd(b,d))})},null,!0);return{Ba:d,ta:c}}
function Ld(a,b,c,d){var e=R(b),f=ed(e.is,e.G),h=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=V(b).o;var g=Md(e,d);return cd(b,e,function(b){var e="";b.f||Fd(b);b.f.cssText&&(e=Hd(a,b.f.cssText,c));b.cssText=e;if(!M&&!Pc(b)&&b.cssText){var k=e=b.cssText;null==b.Z&&(b.Z=Kc.test(e));if(b.Z)if(null==b.K){b.K=[];for(var n in g)k=g[n],k=k(e),e!==k&&(e=k,b.K.push(n))}else{for(n=0;n<b.K.length;++n)k=g[b.K[n]],e=k(e);k=e}b.cssText=k;b.i=b.i||b.selector;e="."+d;n=
b.i.split(",");k=0;for(var t=n.length,B;k<t&&(B=n[k]);k++)n[k]=B.match(h)?B.replace(f,e):e+" "+B;b.selector=n.join(",")}})}function Md(a,b){a=a.b;var c={};if(!M&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,h=b;f.h=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+h;f.i=f.i||f.selector;f.selector=f.i.replace(f.keyframesName,f.a);c[e.keyframesName]=Nd(e)}return c}function Nd(a){return function(b){return b.replace(a.h,a.a)}}
function Od(a,b){var c=Pd,d=Oc(a);a.textContent=O(d,function(a){var d=a.cssText=a.parsedCssText;a.f&&a.f.cssText&&(d=d.replace(Bc,"").replace(Cc,""),a.cssText=Hd(c,d,b))})}q.Object.defineProperties(Dd.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Pd=new Dd;var Qd={},Rd=window.customElements;if(Rd&&!M){var Sd=Rd.define;Rd.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(Q?Q.nextSibling:null)||e.firstChild);Q=d;Qd[a]=d;Sd.call(Rd,a,b,c)}};function Td(){this.cache={}}Td.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({m:b,styleElement:c,l:d});100<e.length&&e.shift();this.cache[a]=e};Td.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var h=c[f];if(e.m[h]!==b[h]){f=!1;break a}}f=!0}if(f)return e}};function Ud(){}
function Vd(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var h=e;var g=[];h.classList?g=Array.from(h.classList):h instanceof window.SVGElement&&h.hasAttribute("class")&&(g=h.getAttribute("class").split(/\s+/));h=g;g=h.indexOf(T.a);if((h=-1<g?h[g+1]:"")&&f===e.ownerDocument)Zc(e,h,!0);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host)){f=R(f).is;g=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+T.a+")");for(var k=0;k<g.length;k++){var l=g[k],m=l.getRootNode().host;m&&(m=R(m).is,ad(l,m))}f!==h&&(h&&Zc(e,h,!0),Zc(e,f))}}}}}
if(!M){var Wd=new MutationObserver(Vd),Xd=function(a){Wd.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Xd(document);else{var Yd=function(){Xd(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Yd):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Yd();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else Yd()})}Ud=function(){Vd(Wd.takeRecords())}}
var Zd=Ud;var $d={};var ae=Promise.resolve();function be(a){if(a=$d[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function ce(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function de(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.a||(a.a=!0,ae.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.a=!1}))};var ee=new Td;function X(){this.B={};this.c=document.documentElement;var a=new oc;a.rules=[];this.h=Ad(this.c,new U(a));this.u=!1;this.b=this.a=null}p=X.prototype;p.ca=function(){Zd()};p.ra=function(a){return Oc(a)};p.Ea=function(a){return O(a)};
p.prepareTemplate=function(a,b,c){if(!a.b){a.b=!0;a.name=b;a.extends=c;$d[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),h=0;h<f.length;h++){var g=f[h];if(g.hasAttribute("shady-unscoped")){if(!M){var k=g.textContent;Nc.has(k)||(Nc.add(k),k=g.cloneNode(!0),document.head.appendChild(k));g.parentNode.removeChild(g)}}else e.push(g.textContent),g.parentNode.removeChild(g)}e=e.join("").trim();c={is:b,extends:c,Ia:d};
M||Zc(a.content,b);Y(this);f=Ic.test(e)||Hc.test(e);Ic.lastIndex=0;Hc.lastIndex=0;e=pc(e);f&&N&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.c=d;d=[];N||(d=Ed(a._styleAst));if(!d.length||N)e=M?a.content:null,b=Qd[b],f=cd(c,a._styleAst),b=f.length?Qc(f,c.is,e,b):void 0,a.Y=b;a.ma=d}};
function fe(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.ba(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.u)&&a.flushCustomStyles()})})}function Y(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=be);fe(a)}
p.flushCustomStyles=function(){Y(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(N)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&N&&this.a){var d=Oc(c);Y(this);this.a.transformRules(d);c.textContent=O(d)}}else for(ge(this,this.c,this.h),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&Od(c,this.h.s);this.b.enqueued=!1;this.u&&!N&&this.styleDocument()}}};
p.styleElement=function(a,b){var c=R(a).is,d=V(a);if(!d){var e=R(a);d=e.is;e=e.G;var f=Qd[d];d=$d[d];if(d){var h=d._styleAst;var g=d.ma}d=Ad(a,new U(h,f,g,e))}a!==this.c&&(this.u=!0);b&&(d.v=d.v||{},Object.assign(d.v,b));if(N){if(d.v){b=d.v;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=$d[c])||a===this.c)&&k&&k.Y&&!ce(k)){if(ce(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)Y(this),this.a&&this.a.transformRules(k._styleAst,c),k.Y.textContent=cd(a,
d.o),de(k);M&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=cd(a,d.o));d.o=k._styleAst}}else if(ge(this,a,d),d.T&&d.T.length){c=d;k=R(a).is;d=(b=ee.fetch(k,c.s,c.T))?b.styleElement:null;h=c.l;(g=b&&b.l)||(g=this.B[k]=(this.B[k]||0)+1,g=k+"-"+g);c.l=g;g=c.l;e=Pd;e=d?d.textContent||"":Ld(e,a,c.s,g);f=V(a);var l=f.a;l&&!M&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));M?f.a?(f.a.textContent=e,d=f.a):e&&(d=Qc(e,g,a.shadowRoot,f.b)):d?d.parentNode||(Cd&&-1<
e.indexOf("@media")&&(d.textContent=e),Rc(d,null,f.b)):e&&(d=Qc(e,g,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);g=d;M||(d=c.l,f=e=a.getAttribute("class")||"",h&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+h+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&Tc(a,f));b||ee.store(k,c.s,g,c.l)}};function he(a,b){return(b=b.getRootNode().host)?V(b)?b:he(a,b):a.c}
function ge(a,b,c){a=he(a,b);var d=V(a);a=Object.create(d.s||null);var e=Kd(b,c.o);b=Id(d.o,b).m;Object.assign(a,e.ta,b,e.Ba);b=c.v;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Pd;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=W(f,a[d],a);c.s=a}p.styleDocument=function(a){this.styleSubtree(this.c,a)};
p.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};p.ba=function(a){var b=this,c=Oc(a);P(c,function(a){if(M)xd(a);else{var c=T;a.selector=a.parsedSelector;xd(a);a.selector=a.i=gd(c,a,c.c,void 0,void 0)}N&&(Y(b),b.a&&b.a.transformRule(a))});N?a.textContent=O(c):this.h.o.rules.push(c)};
p.getComputedStyleValue=function(a,b){var c;N||(c=(V(a)||V(he(this,a))).s[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};p.Da=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===T.a){c=d[e+1];break}}}c&&b.push(T.a,c);N||(c=V(a))&&c.l&&b.push(Pd.a,c.l);Tc(a,b.join(" "))};p.na=function(a){return V(a)};X.prototype.flush=X.prototype.ca;
X.prototype.prepareTemplate=X.prototype.prepareTemplate;X.prototype.styleElement=X.prototype.styleElement;X.prototype.styleDocument=X.prototype.styleDocument;X.prototype.styleSubtree=X.prototype.styleSubtree;X.prototype.getComputedStyleValue=X.prototype.getComputedStyleValue;X.prototype.setElementClass=X.prototype.Da;X.prototype._styleInfoForNode=X.prototype.na;X.prototype.transformCustomStyleForDocument=X.prototype.ba;X.prototype.getStyleAst=X.prototype.ra;X.prototype.styleAstToString=X.prototype.Ea;
X.prototype.flushCustomStyles=X.prototype.flushCustomStyles;Object.defineProperties(X.prototype,{nativeShadow:{get:function(){return M}},nativeCss:{get:function(){return N}}});var Z=new X,ie,je;window.ShadyCSS&&(ie=window.ShadyCSS.ApplyShim,je=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:N,nativeShadow:M};ie&&(window.ShadyCSS.ApplyShim=ie);
je&&(window.ShadyCSS.CustomStyleInterface=je);/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var ke=window.customElements,le=window.HTMLImports,me=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(ke&&ke.polyfillWrapFlushCallback){var ne,oe=function(){if(ne){me.oa&&me.oa(window.document);var a=ne;ne=null;a();return!0}},pe=le.whenReady;ke.polyfillWrapFlushCallback(function(a){ne=a;pe(oe)});le.whenReady=function(a){pe(function(){oe()?le.whenReady(a):a()})}}
le.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var qe=document.createElement("style");qe.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var re=document.querySelector("head");re.insertBefore(qe,re.firstChild);/*

Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-sd.js.map
