(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var n,p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function ba(){ba=function(){};p.Symbol||(p.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function da(){ba();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(this)}});da=function(){}}function ea(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){da();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function ha(a){da();var b=a[Symbol.iterator];return b?b.call(a):ea(a)}
function ia(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var r=window.ShadyDOM||{};r.ua=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ja=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");r.D=!!(ja&&ja.configurable&&ja.get);r.ea=r.force||!r.ua;function t(a){return a.__shady&&void 0!==a.__shady.firstChild}function u(a){return"ShadyRoot"===a.ja}function v(a){a=a.getRootNode();if(u(a))return a}
var w=Element.prototype,ka=w.matches||w.matchesSelector||w.mozMatchesSelector||w.msMatchesSelector||w.oMatchesSelector||w.webkitMatchesSelector;function la(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function ma(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)la(a,c[d]);return a}function na(a,b){for(var c in b)a[c]=b[c]}
var oa=document.createTextNode(""),pa=0,qa=[];(new MutationObserver(function(){for(;qa.length;)try{qa.shift()()}catch(a){throw oa.textContent=pa++,a;}})).observe(oa,{characterData:!0});function ra(a){qa.push(a);oa.textContent=pa++}var sa=!!document.contains;function ta(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1};var ua=[],va;function wa(a){va||(va=!0,ra(xa));ua.push(a)}function xa(){va=!1;for(var a=!!ua.length;ua.length;)ua.shift()();return a}xa.list=ua;function ya(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.L=new Set}function za(a){a.a||(a.a=!0,ra(function(){Aa(a)}))}function Aa(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.L.forEach(function(a){a(b)})}}ya.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ba(a,b){a.__shady=a.__shady||{};a.__shady.F||(a.__shady.F=new ya);a.__shady.F.L.add(b);var c=a.__shady.F;return{ma:b,v:c,pa:a,takeRecords:function(){return c.takeRecords()}}}function Ca(a){var b=a&&a.v;b&&(b.L.delete(a.ma),b.L.size||(a.pa.__shady.F=null))}
function Da(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var x={},Ea=Element.prototype.insertBefore,Fa=Element.prototype.removeChild,Ga=Element.prototype.setAttribute,Ha=Element.prototype.removeAttribute,Ia=Element.prototype.cloneNode,Ja=Document.prototype.importNode,Ka=Element.prototype.addEventListener,La=Element.prototype.removeEventListener,Ma=Window.prototype.addEventListener,Na=Window.prototype.removeEventListener,Oa=Element.prototype.dispatchEvent,Pa=Element.prototype.querySelector,Qa=Element.prototype.querySelectorAll,Ra=Node.prototype.contains||
HTMLElement.prototype.contains;x.appendChild=Element.prototype.appendChild;x.insertBefore=Ea;x.removeChild=Fa;x.setAttribute=Ga;x.removeAttribute=Ha;x.cloneNode=Ia;x.importNode=Ja;x.addEventListener=Ka;x.removeEventListener=La;x.Ea=Ma;x.Fa=Na;x.dispatchEvent=Oa;x.querySelector=Pa;x.querySelectorAll=Qa;x.contains=Ra;var Sa=/[&\u00A0"]/g,Ta=/[&\u00A0<>]/g;function Ua(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Va(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Wa=Va("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Xa=Va("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ya(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,h;e<f&&(h=d[e]);e++){a:{var g=h;var k=a;var l=b;switch(g.nodeType){case Node.ELEMENT_NODE:for(var m=g.localName,q="<"+m,H=g.attributes,P=0;k=H[P];P++)q+=" "+k.name+'="'+k.value.replace(Sa,Ua)+'"';q+=">";g=Wa[m]?q:q+Ya(g,l)+"</"+m+">";break a;case Node.TEXT_NODE:g=g.data;g=k&&Xa[k.localName]?g:g.replace(Ta,Ua);break a;case Node.COMMENT_NODE:g="\x3c!--"+g.data+"--\x3e";break a;default:throw window.console.error(g),
Error("not implemented");}}c+=g}return c};var y={},z=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),A=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function Za(a){var b=[];z.currentNode=a;for(a=z.firstChild();a;)b.push(a),a=z.nextSibling();return b}y.parentNode=function(a){z.currentNode=a;return z.parentNode()};y.firstChild=function(a){z.currentNode=a;return z.firstChild()};y.lastChild=function(a){z.currentNode=a;return z.lastChild()};y.previousSibling=function(a){z.currentNode=a;return z.previousSibling()};
y.nextSibling=function(a){z.currentNode=a;return z.nextSibling()};y.childNodes=Za;y.parentElement=function(a){A.currentNode=a;return A.parentNode()};y.firstElementChild=function(a){A.currentNode=a;return A.firstChild()};y.lastElementChild=function(a){A.currentNode=a;return A.lastChild()};y.previousElementSibling=function(a){A.currentNode=a;return A.previousSibling()};y.nextElementSibling=function(a){A.currentNode=a;return A.nextSibling()};
y.children=function(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return b};y.innerHTML=function(a){return Ya(a,function(a){return Za(a)})};y.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var $a=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),ab=document.implementation.createHTMLDocument("inert"),bb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),cb={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentNode;a&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:y.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;
return void 0!==a?a:y.parentNode(this)},configurable:!0},nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:y.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;return void 0!==a?a:y.previousSibling(this)},configurable:!0},className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&
void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return y.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return y.previousElementSibling(this)},configurable:!0}},db={childNodes:{get:function(){if(t(this)){if(!this.__shady.childNodes){this.__shady.childNodes=
[];for(var a=this.firstChild;a;a=a.nextSibling)this.__shady.childNodes.push(a)}var b=this.__shady.childNodes}else b=y.childNodes(this);b.item=function(a){return b[a]};return b},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=this.__shady&&this.__shady.firstChild;return void 0!==a?a:y.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;return void 0!==a?a:y.lastChild(this)},
configurable:!0},textContent:{get:function(){if(t(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return y.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(;this.firstChild;)this.removeChild(this.firstChild);(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=
a}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return y.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return y.lastElementChild(this)},configurable:!0},children:{get:function(){var a=t(this)?
Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE}):y.children(this);a.item=function(b){return a[b]};return a},configurable:!0},innerHTML:{get:function(){var a="template"===this.localName?this.content:this;return t(this)?Ya(a):y.innerHTML(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);var c=this.localName;c&&"template"!==c||(c="div");c=ab.createElement(c);for($a&&$a.set?$a.set.call(c,
a):c.innerHTML=a;c.firstChild;)b.appendChild(c.firstChild)},configurable:!0}},eb={shadowRoot:{get:function(){return this.__shady&&this.__shady.ya||null},configurable:!0}},fb={activeElement:{get:function(){var a=bb&&bb.get?bb.get.call(document):r.D?void 0:document.activeElement;if(a&&a.nodeType){var b=!!u(this);if(this===document||b&&this.host!==a&&x.contains.call(this.host,a)){for(b=v(a);b&&b!==this;)a=b.host,b=v(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},
configurable:!0}};function B(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function C(a){B(a,cb);B(a,db);B(a,fb)}var gb=r.D?function(){}:function(a){a.__shady&&a.__shady.ka||(a.__shady=a.__shady||{},a.__shady.ka=!0,B(a,cb,!0))},hb=r.D?function(){}:function(a){a.__shady&&a.__shady.ia||(a.__shady=a.__shady||{},a.__shady.ia=!0,B(a,db,!0),B(a,eb,!0))};function ib(a,b,c){gb(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&(b.__shady.firstChild=a):(b.__shady.lastChild=a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}
function jb(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=y.firstChild(a);a.__shady.lastChild=y.lastChild(a);hb(a);for(var b=a.__shady.childNodes=y.childNodes(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,gb(d)}};function kb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==d&&d!==a||void 0===d&&y.parentNode(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&lb(b.parentNode,b);d=v(a);var e;if(e=d)a:{if(!b.__noInsertionPoint){var f;"slot"===b.localName?f=[b]:
b.querySelectorAll&&(f=b.querySelectorAll("slot"));if(f&&f.length){e=f;break a}}e=void 0}(f=e)&&d.B.push.apply(d.B,[].concat(f instanceof Array?f:ia(ha(f))));d&&("slot"===a.localName||f)&&D(d);if(t(a)){d=c;hb(a);a.__shady=a.__shady||{};void 0!==a.__shady.firstChild&&(a.__shady.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(e=0;e<f.length;e++)ib(f[e],a,d);b.__shady=b.__shady||{};d=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=b.__shady.lastChild=d;
b.__shady.childNodes=d}else ib(b,a,d);if(mb(a)){D(a.__shady.root);var h=!0}else a.__shady.root&&(h=!0)}h||(h=u(a)?a.host:a,c?(c=nb(c),x.insertBefore.call(h,b,c)):x.appendChild.call(h,b));ob(a,b);return b}
function lb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=v(b);if(t(a)){b.__shady=b.__shady||{};a.__shady=a.__shady||{};b===a.__shady.firstChild&&(a.__shady.firstChild=b.__shady.nextSibling);b===a.__shady.lastChild&&(a.__shady.lastChild=b.__shady.previousSibling);var d=b.__shady.previousSibling,e=b.__shady.nextSibling;d&&(d.__shady=d.__shady||{},d.__shady.nextSibling=e);e&&(e.__shady=e.__shady||{},e.__shady.previousSibling=d);b.__shady.parentNode=
b.__shady.previousSibling=b.__shady.nextSibling=void 0;void 0!==a.__shady.childNodes&&(a.__shady.childNodes=null);if(mb(a)){D(a.__shady.root);var f=!0}}pb(b);if(c){(d=a&&"slot"===a.localName)&&(f=!0);qb(c);e=c.i;for(var h in e)for(var g=e[h],k=0;k<g.length;k++){var l=g[k];if(ta(b,l)){g.splice(k,1);var m=c.l.indexOf(l);0<=m&&c.l.splice(m,1);k--;if(m=l.__shady.C)for(l=0;l<m.length;l++){var q=m[l],H=y.parentNode(q);H&&x.removeChild.call(H,q)}m=!0}}(m||d)&&D(c)}f||(f=u(a)?a.host:a,(!a.__shady.root&&"slot"!==
b.localName||f===y.parentNode(b))&&x.removeChild.call(f,b));ob(a,null,b);return b}function pb(a){if(a.__shady&&void 0!==a.__shady.$)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)pb(e);a.__shady&&(a.__shady.$=void 0)}function nb(a){var b=a;a&&"slot"===a.localName&&(b=(b=a.__shady&&a.__shady.C)&&b.length?b[0]:nb(a.nextSibling));return b}function mb(a){return(a=a&&a.__shady&&a.__shady.root)&&rb(a)}
function sb(a,b){if("slot"===b)a=a.parentNode,mb(a)&&D(a.__shady.root);else if("slot"===a.localName&&"name"===b&&(b=v(a))){var c=a.la,d=tb(a);if(d!==c){c=b.i[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.i[d]||(b.i[d]=[]);c.push(a);1<c.length&&(b.i[d]=ub(c))}D(b)}}function ob(a,b,c){if(a=a.__shady&&a.__shady.F)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),za(a)}
function vb(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.$;void 0===b&&(b=u(a)?a:(b=a.parentNode)?vb(b):a,x.contains.call(document.documentElement,a)&&(a.__shady.$=b));return b}}function wb(a,b,c){var d=[];xb(a.childNodes,b,c,d);return d}function xb(a,b,c,d){for(var e=0,f=a.length,h;e<f&&(h=a[e]);e++){var g;if(g=h.nodeType===Node.ELEMENT_NODE){g=h;var k=b,l=c,m=d,q=k(g);q&&m.push(g);l&&l(q)?g=q:(xb(g.childNodes,k,l,m),g=void 0)}if(g)break}}var yb=null;
function zb(a,b,c){yb||(yb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);yb&&"class"===b?yb.setElementClass(a,c):(x.setAttribute.call(a,b,c),sb(a,b))}function Ab(a,b){if(a.ownerDocument!==document)return x.importNode.call(document,a,b);var c=x.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Ab(a[b],!0),c.appendChild(d)}return c};var Bb="__eventWrappers"+Date.now(),Cb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,
dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0};function Db(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}
function Eb(a,b){if(!u)return a;a=Db(a,!0);for(var c=0,d,e,f,h;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(h=a.indexOf(f),e=f),!u(f)||-1<h)return d}
var Fb={get composed(){!1!==this.isTrusted&&void 0===this.P&&(this.P=Cb[this.type]);return this.P||!1},composedPath:function(){this.b||(this.b=Db(this.__target,this.composed));return this.b},get target(){return Eb(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.R)return null;this.c||(this.c=Db(this.R,!0));return Eb(this.currentTarget,this.c)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.a=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
this.a=this.g=!0}};function Gb(a){function b(b,d){b=new a(b,d);b.P=d&&!!d.composed;return b}na(b,a);b.prototype=a.prototype;return b}var Hb={focus:!0,blur:!0};function Ib(a){return a.__target!==a.target||a.R!==a.relatedTarget}function Jb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!Ib(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.g);d++);}
function Kb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];Jb(a,d,"capture");if(a.a)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=d.__shady&&d.__shady.root;if(0===c||f&&f===e)if(Jb(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.a)break}}
function Lb(a,b,c,d,e,f){for(var h=0;h<a.length;h++){var g=a[h],k=g.type,l=g.capture,m=g.once,q=g.passive;if(b===g.node&&c===k&&d===l&&e===m&&f===q)return h}return-1}
function Mb(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var h=!!c.passive}else e=!!c,h=f=!1;var g=c&&c.S||this,k=b[Bb];if(k){if(-1<Lb(k,g,a,e,f,h))return}else b[Bb]=[];k=function(e){f&&this.removeEventListener(a,b,c);e.__target||Nb(e);if(g!==this){var h=Object.getOwnPropertyDescriptor(e,"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return g},
configurable:!0})}if(e.composed||-1<e.composedPath().indexOf(g))if(Ib(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===g||g instanceof Window){var k="function"===d?b.call(g,e):b.handleEvent&&b.handleEvent(e);g!==this&&(h?(Object.defineProperty(e,"currentTarget",h),h=null):delete e.currentTarget);return k}};b[Bb].push({node:this,type:a,capture:e,once:f,passive:h,Ga:k});Hb[a]?(this.__handlers=
this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(k)):(this instanceof Window?x.Ea:x.addEventListener).call(this,a,k,c)}}}
function Ob(a,b,c){if(b){if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var h=c&&c.S||this,g=void 0;var k=null;try{k=b[Bb]}catch(l){}k&&(e=Lb(k,h,a,d,e,f),-1<e&&(g=k.splice(e,1)[0].Ga,k.length||(b[Bb]=void 0)));(this instanceof Window?x.Fa:x.removeEventListener).call(this,a,g||b,c);g&&Hb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],g=a.indexOf(g),-1<g&&a.splice(g,1))}}
function Pb(){for(var a in Hb)window.addEventListener(a,function(a){a.__target||(Nb(a),Kb(a))},!0)}function Nb(a){a.__target=a.target;a.R=a.relatedTarget;if(r.D){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Ia=b;la(c,Fb);b.__patchProto=c}a.__proto__=b.__patchProto}else la(a,Fb)}var Qb=Gb(window.Event),Rb=Gb(window.CustomEvent),Sb=Gb(window.MouseEvent);function Tb(a,b){return{index:a,G:[],K:b}}
function Ub(a,b,c,d){var e=0,f=0,h=0,g=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(h=0;h<k;h++)if(a[h]!==c[h])break a;h=k}if(b==a.length&&d==c.length){g=a.length;for(var l=c.length,m=0;m<k-h&&Vb(a[--g],c[--l]);)m++;g=m}e+=h;f+=h;b-=g;d-=g;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Tb(e,0);f<d;)b.G.push(c[f++]);return[b]}if(f==d)return[Tb(e,b-e)];k=e;h=f;d=d-h+1;g=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(g),b[l][0]=l;for(l=0;l<g;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<g;m++)if(a[k+m-1]===c[h+l-1])b[l][m]=
b[l-1][m-1];else{var q=b[l-1][m]+1,H=b[l][m-1]+1;b[l][m]=q<H?q:H}k=b.length-1;h=b[0].length-1;d=b[k][h];for(a=[];0<k||0<h;)0==k?(a.push(2),h--):0==h?(a.push(3),k--):(g=b[k-1][h-1],l=b[k-1][h],m=b[k][h-1],q=l<m?l<g?l:g:m<g?m:g,q==g?(g==d?a.push(0):(a.push(1),d=g),k--,h--):q==l?(a.push(3),k--,d=l):(a.push(2),h--,d=m));a.reverse();b=void 0;k=[];for(h=0;h<a.length;h++)switch(a[h]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=Tb(e,0));b.K++;e++;b.G.push(c[f]);f++;break;case 2:b||(b=Tb(e,0));
b.K++;e++;break;case 3:b||(b=Tb(e,0)),b.G.push(c[f]),f++}b&&k.push(b);return k}function Vb(a,b){return a===b};var Wb={};function E(a,b,c){if(a!==Wb)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=E.prototype;a.ja="ShadyRoot";jb(b);jb(a);a.host=b;a.oa=c&&c.mode;b.__shady=b.__shady||{};b.__shady.root=a;b.__shady.ya="closed"!==a.oa?a:null;a.J=!1;a.l=[];a.i={};a.B=[];c=y.childNodes(b);for(var d=0,e=c.length;d<e;d++)x.removeChild.call(b,c[d]);return a}E.prototype=Object.create(DocumentFragment.prototype);function D(a){a.J||(a.J=!0,wa(function(){return Xb(a)}))}
function Xb(a){for(var b;a;){a.J&&(b=a);a:{var c=a;a=c.host.getRootNode();if(u(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
E.prototype._renderRoot=function(){this.J=!1;qb(this);for(var a=0,b;a<this.l.length;a++){b=this.l[a];var c=b.__shady.assignedNodes;b.__shady.assignedNodes=[];b.__shady.C=[];if(b.__shady.aa=c)for(var d=0;d<c.length;d++){var e=c[d];e.__shady.W=e.__shady.assignedSlot;e.__shady.assignedSlot===b&&(e.__shady.assignedSlot=null)}}for(b=this.host.firstChild;b;b=b.nextSibling)Yb(this,b);for(a=0;a<this.l.length;a++){b=this.l[a];if(!b.__shady.assignedNodes.length)for(c=b.firstChild;c;c=c.nextSibling)Yb(this,
c,b);c=b.parentNode;(c=c.__shady&&c.__shady.root)&&rb(c)&&c._renderRoot();Zb(this,b.__shady.C,b.__shady.assignedNodes);if(c=b.__shady.aa){for(d=0;d<c.length;d++)c[d].__shady.W=null;b.__shady.aa=null;c.length>b.__shady.assignedNodes.length&&(b.__shady.Y=!0)}b.__shady.Y&&(b.__shady.Y=!1,$b(this,b))}a=this.l;b=[];for(c=0;c<a.length;c++)d=a[c].parentNode,d.__shady&&d.__shady.root||!(0>b.indexOf(d))||b.push(d);for(a=0;a<b.length;a++){c=b[a];d=c===this?this.host:c;e=[];c=c.childNodes;for(var f=0;f<c.length;f++){var h=
c[f];if("slot"==h.localName){h=h.__shady.C;for(var g=0;g<h.length;g++)e.push(h[g])}else e.push(h)}c=void 0;f=y.childNodes(d);h=Ub(e,e.length,f,f.length);for(var k=g=0;g<h.length&&(c=h[g]);g++){for(var l=0,m;l<c.G.length&&(m=c.G[l]);l++)y.parentNode(m)===d&&x.removeChild.call(d,m),f.splice(c.index+k,1);k-=c.K}for(k=0;k<h.length&&(c=h[k]);k++)for(g=f[c.index],l=c.index;l<c.index+c.K;l++)m=e[l],x.insertBefore.call(d,m,g),f.splice(l,0,m)}};
function Yb(a,b,c){b.__shady=b.__shady||{};var d=b.__shady.W;b.__shady.W=null;c||(c=(a=a.i[b.slot||"__catchall"])&&a[0]);c?(c.__shady.assignedNodes.push(b),b.__shady.assignedSlot=c):b.__shady.assignedSlot=void 0;d!==b.__shady.assignedSlot&&b.__shady.assignedSlot&&(b.__shady.assignedSlot.__shady.Y=!0)}function Zb(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=e.__shady.assignedNodes;f&&f.length&&Zb(a,b,f)}else b.push(c[d])}
function $b(a,b){x.dispatchEvent.call(b,new Event("slotchange"));b.__shady.assignedSlot&&$b(a,b.__shady.assignedSlot)}function qb(a){if(a.B.length){for(var b=a.B,c,d=0;d<b.length;d++){var e=b[d];e.__shady=e.__shady||{};jb(e);jb(e.parentNode);var f=tb(e);a.i[f]?(c=c||{},c[f]=!0,a.i[f].push(e)):a.i[f]=[e];a.l.push(e)}if(c)for(var h in c)a.i[h]=ub(a.i[h]);a.B=[]}}function tb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.la=b}
function ub(a){return a.sort(function(a,c){a=ac(a);for(var b=ac(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}function ac(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}function rb(a){qb(a);return!!a.l.length}E.prototype.addEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.S=this;this.host.addEventListener(a,b,c)};
E.prototype.removeEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.S=this;this.host.removeEventListener(a,b,c)};E.prototype.getElementById=function(a){return wb(this,function(b){return b.id==a},function(a){return!!a})[0]||null};var bc=E.prototype;B(bc,db,!0);B(bc,fb,!0);function cc(a){var b=a.getRootNode();u(b)&&Xb(b);return a.__shady&&a.__shady.assignedSlot||null}
var dc={addEventListener:Mb.bind(window),removeEventListener:Ob.bind(window)},ec={addEventListener:Mb,removeEventListener:Ob,appendChild:function(a){return kb(this,a)},insertBefore:function(a,b){return kb(this,a,b)},removeChild:function(a){return lb(this,a)},replaceChild:function(a,b){kb(this,a,b);lb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=x.cloneNode.call(this,a);else if(b=x.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return vb(this)},contains:function(a){return ta(this,a)},get isConnected(){var a=this.ownerDocument;if(sa&&x.contains.call(a,this)||a.documentElement&&x.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(a instanceof E?a.host:void 0);return!!(a&&a instanceof Document)},dispatchEvent:function(a){xa();return x.dispatchEvent.call(this,a)}},fc={get assignedSlot(){return cc(this)}},
gc={querySelector:function(a){return wb(this,function(b){return ka.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a){return wb(this,function(b){return ka.call(b,a)})}},hc={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();u(b)&&Xb(b);return this.__shady?(a&&a.flatten?this.__shady.C:this.__shady.assignedNodes)||[]:[]}}},ic=ma({setAttribute:function(a,b){zb(this,a,b)},removeAttribute:function(a){x.removeAttribute.call(this,a);sb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";
if(!a)throw"Not enough arguments.";return new E(Wb,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){zb(this,"slot",a)},get assignedSlot(){return cc(this)}},gc,hc);Object.defineProperties(ic,eb);var jc=ma({importNode:function(a,b){return Ab(a,b)},getElementById:function(a){return wb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},gc);Object.defineProperties(jc,{_activeElement:fb.activeElement});
var kc=HTMLElement.prototype.blur,lc=ma({blur:function(){var a=this.__shady&&this.__shady.root;(a=a&&a.activeElement)?a.blur():kc.call(this)}});function F(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(r.ea){var ShadyDOM={inUse:r.ea,patch:function(a){return a},isShadyRoot:u,enqueue:wa,flush:xa,settings:r,filterMutations:Da,observeChildren:Ba,unobserveChildren:Ca,nativeMethods:x,nativeTree:y};window.ShadyDOM=ShadyDOM;window.Event=Qb;window.CustomEvent=Rb;window.MouseEvent=Sb;Pb();var mc=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;F(window.Node.prototype,ec);F(window.Window.prototype,dc);F(window.Text.prototype,fc);F(window.DocumentFragment.prototype,gc);F(window.Element.prototype,
ic);F(window.Document.prototype,jc);window.HTMLSlotElement&&F(window.HTMLSlotElement.prototype,hc);F(mc.prototype,lc);r.D&&(C(window.Node.prototype),C(window.Text.prototype),C(window.DocumentFragment.prototype),C(window.Element.prototype),C(mc.prototype),C(window.Document.prototype),window.HTMLSlotElement&&C(window.HTMLSlotElement.prototype));window.ShadowRoot=E};var nc=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function oc(a){var b=nc.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function G(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function pc(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function I(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)I(d,b,c);d=pc(a,e);continue}else if("template"===f){d=pc(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)I(e,b,c)}d=d.firstChild?d.firstChild:pc(a,d)}}function J(a,b,c){a[b]=c};function qc(){this.a=new Map;this.w=new Map;this.g=[];this.c=!1}function rc(a,b,c){a.a.set(b,c);a.w.set(c.constructor,c)}function sc(a,b){a.c=!0;a.g.push(b)}function tc(a,b){a.c&&I(b,function(b){return a.b(b)})}qc.prototype.b=function(a){if(this.c&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.g.length;b++)this.g[b](a)}};function K(a,b){var c=[];I(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):uc(a,d)}}
function L(a,b){var c=[];I(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function M(a,b,c){c=void 0===c?{}:c;var d=c.Da||new Set,e=c.O||function(b){return uc(a,b)},f=[];I(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var c=b.import;c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:b.addEventListener("load",function(){var c=b.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f.delete(c);M(a,c,{Da:f,O:e})}})}else f.push(b)},d);if(a.c)for(b=
0;b<f.length;b++)a.b(f[b]);for(b=0;b<f.length;b++)e(f[b])}
function uc(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.a.get(b.localName)){c.constructionStack.push(b);var d=c.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(h){throw b.__CE_state=2,h;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=c[d],
f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}G(b)&&a.connectedCallback(b)}}}qc.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};qc.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
qc.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function vc(a){var b=document;this.f=a;this.a=b;this.v=void 0;M(this.f,this.a);"loading"===this.a.readyState&&(this.v=new MutationObserver(this.b.bind(this)),this.v.observe(this.a,{childList:!0,subtree:!0}))}function wc(a){a.v&&a.v.disconnect()}vc.prototype.b=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||wc(this);for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)M(this.f,c[d])};function xc(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}function yc(a){if(a.a)throw Error("Already resolved.");a.a=void 0;a.b&&a.b(void 0)};function N(a){this.T=!1;this.f=a;this.X=new Map;this.U=function(a){return a()};this.I=!1;this.V=[];this.na=new vc(a)}n=N.prototype;
n.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!oc(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.f.a.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.T)throw Error("A custom element is already being defined.");this.T=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var h=d("disconnectedCallback");var g=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(m){return}finally{this.T=!1}b={localName:a,constructor:b,connectedCallback:f,disconnectedCallback:h,adoptedCallback:g,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};rc(this.f,a,b);this.V.push(b);
this.I||(this.I=!0,this.U(function(){return zc(c)}))};n.O=function(a){M(this.f,a)};function zc(a){if(!1!==a.I){a.I=!1;for(var b=a.V,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);M(a.f,document,{O:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.f.a.get(e)&&c.push(b)}}});for(e=0;e<c.length;e++)uc(a.f,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var h=0;h<f.length;h++)uc(a.f,f[h]);(e=a.X.get(e))&&yc(e)}}}
n.get=function(a){if(a=this.f.a.get(a))return a.constructor};n.ga=function(a){if(!oc(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.X.get(a);if(b)return b.c;b=new xc;this.X.set(a,b);this.f.a.get(a)&&!this.V.some(function(b){return b.localName===a})&&yc(b);return b.c};n.xa=function(a){wc(this.na);var b=this.U;this.U=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=N;N.prototype.define=N.prototype.define;
N.prototype.upgrade=N.prototype.O;N.prototype.get=N.prototype.get;N.prototype.whenDefined=N.prototype.ga;N.prototype.polyfillWrapFlushCallback=N.prototype.xa;var Ac=window.Document.prototype.createElement,Bc=window.Document.prototype.createElementNS,Cc=window.Document.prototype.importNode,Dc=window.Document.prototype.prepend,Ec=window.Document.prototype.append,Fc=window.DocumentFragment.prototype.prepend,Gc=window.DocumentFragment.prototype.append,Hc=window.Node.prototype.cloneNode,Ic=window.Node.prototype.appendChild,Jc=window.Node.prototype.insertBefore,Kc=window.Node.prototype.removeChild,Lc=window.Node.prototype.replaceChild,Mc=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),Nc=window.Element.prototype.attachShadow,Oc=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),Pc=window.Element.prototype.getAttribute,Qc=window.Element.prototype.setAttribute,Rc=window.Element.prototype.removeAttribute,Sc=window.Element.prototype.getAttributeNS,Tc=window.Element.prototype.setAttributeNS,Uc=window.Element.prototype.removeAttributeNS,Vc=window.Element.prototype.insertAdjacentElement,Wc=window.Element.prototype.insertAdjacentHTML,Xc=window.Element.prototype.prepend,
Yc=window.Element.prototype.append,Zc=window.Element.prototype.before,$c=window.Element.prototype.after,ad=window.Element.prototype.replaceWith,bd=window.Element.prototype.remove,cd=window.HTMLElement,dd=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),ed=window.HTMLElement.prototype.insertAdjacentElement,fd=window.HTMLElement.prototype.insertAdjacentHTML;var gd=new function(){};function hd(){var a=O;window.HTMLElement=function(){function b(){var b=this.constructor,d=a.w.get(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=Ac.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.b(e),e;d=e.length-1;var f=e[d];if(f===gd)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=gd;Object.setPrototypeOf(f,b.prototype);a.b(f);return f}b.prototype=cd.prototype;return b}()};function id(a,b,c){function d(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var f=[],l=0;l<d.length;l++){var m=d[l];m instanceof Element&&G(m)&&f.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)e.push(m);else e.push(m)}b.apply(this,d);for(d=0;d<f.length;d++)L(a,f[d]);if(G(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&K(a,f)}}void 0!==c.N&&(b.prepend=d(c.N));void 0!==c.append&&(b.append=d(c.append))};function jd(){var a=O;J(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.a.get(b);if(c)return new c.constructor}b=Ac.call(this,b);a.b(b);return b});J(Document.prototype,"importNode",function(b,c){b=Cc.call(this,b,c);this.__CE_hasRegistry?M(a,b):tc(a,b);return b});J(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.a.get(c);if(d)return new d.constructor}b=Bc.call(this,b,c);a.b(b);return b});
id(a,Document.prototype,{N:Dc,append:Ec})};function kd(){var a=O;function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,g=e.length;if(0<g&&G(this)){c=Array(g);for(var k=0;k<g;k++)c[k]=e[k]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)L(a,c[b])}}})}J(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);
b=Jc.call(this,b,d);if(G(this))for(d=0;d<c.length;d++)K(a,c[d]);return b}c=G(b);d=Jc.call(this,b,d);c&&L(a,b);G(this)&&K(a,b);return d});J(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Ic.call(this,b);if(G(this))for(var e=0;e<c.length;e++)K(a,c[e]);return b}c=G(b);e=Ic.call(this,b);c&&L(a,b);G(this)&&K(a,b);return e});J(Node.prototype,"cloneNode",function(b){b=Hc.call(this,b);this.ownerDocument.__CE_hasRegistry?M(a,b):
tc(a,b);return b});J(Node.prototype,"removeChild",function(b){var c=G(b),e=Kc.call(this,b);c&&L(a,b);return e});J(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Lc.call(this,b,d);if(G(this))for(L(a,d),d=0;d<c.length;d++)K(a,c[d]);return b}c=G(b);var f=Lc.call(this,b,d),h=G(this);h&&L(a,d);c&&L(a,b);h&&K(a,b);return f});Mc&&Mc.get?b(Node.prototype,Mc):sc(a,function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=
[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)Kc.call(this,this.firstChild);Ic.call(this,document.createTextNode(a))}})})};function ld(a){var b=Element.prototype;function c(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var g=[],k=0;k<d.length;k++){var l=d[k];l instanceof Element&&G(l)&&g.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)e.push(l);else e.push(l)}b.apply(this,d);for(d=0;d<g.length;d++)L(a,g[d]);if(G(this))for(d=0;d<e.length;d++)g=e[d],g instanceof Element&&K(a,g)}}void 0!==Zc&&(b.before=c(Zc));void 0!==Zc&&(b.after=c($c));void 0!==
ad&&J(b,"replaceWith",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];d=[];for(var h=[],g=0;g<c.length;g++){var k=c[g];k instanceof Element&&G(k)&&h.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)d.push(k);else d.push(k)}g=G(this);ad.apply(this,c);for(c=0;c<h.length;c++)L(a,h[c]);if(g)for(L(a,this),c=0;c<d.length;c++)h=d[c],h instanceof Element&&K(a,h)});void 0!==bd&&J(b,"remove",function(){var b=G(this);bd.call(this);b&&L(a,this)})};function md(){var a=O;function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;G(this)&&(e=[],I(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var h=e[f];1===h.__CE_state&&a.disconnectedCallback(h)}this.ownerDocument.__CE_hasRegistry?M(a,this):tc(a,this);return b}})}function c(b,c){J(b,"insertAdjacentElement",function(b,d){var e=G(d);b=c.call(this,b,d);e&&L(a,d);G(b)&&K(a,d);
return b})}function d(b,c){function d(b,c){for(var d=[];b!==c;b=b.nextSibling)d.push(b);for(c=0;c<d.length;c++)M(a,d[c])}J(b,"insertAdjacentHTML",function(a,b){a=a.toLowerCase();if("beforebegin"===a){var e=this.previousSibling;c.call(this,a,b);d(e||this.parentNode.firstChild,this)}else if("afterbegin"===a)e=this.firstChild,c.call(this,a,b),d(this.firstChild,e);else if("beforeend"===a)e=this.lastChild,c.call(this,a,b),d(e||this.firstChild,null);else if("afterend"===a)e=this.nextSibling,c.call(this,
a,b),d(this.nextSibling,e);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}Nc&&J(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=Nc.call(this,a)});Oc&&Oc.get?b(Element.prototype,Oc):dd&&dd.get?b(HTMLElement.prototype,dd):sc(a,function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return Hc.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:
this,d=Ac.call(document,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)Kc.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)Ic.call(c,a.childNodes[0])}})});J(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return Qc.call(this,b,c);var d=Pc.call(this,b);Qc.call(this,b,c);c=Pc.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});J(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return Tc.call(this,b,c,d);var e=Sc.call(this,
b,c);Tc.call(this,b,c,d);d=Sc.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});J(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return Rc.call(this,b);var c=Pc.call(this,b);Rc.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});J(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return Uc.call(this,b,c);var d=Sc.call(this,b,c);Uc.call(this,b,c);var e=Sc.call(this,b,c);d!==e&&a.attributeChangedCallback(this,c,d,e,b)});ed?
c(HTMLElement.prototype,ed):Vc?c(Element.prototype,Vc):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");fd?d(HTMLElement.prototype,fd):Wc?d(Element.prototype,Wc):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");id(a,Element.prototype,{N:Xc,append:Yc});ld(a)};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var nd=window.customElements;if(!nd||nd.forcePolyfill||"function"!=typeof nd.define||"function"!=typeof nd.get){var O=new qc;hd();jd();id(O,DocumentFragment.prototype,{N:Fc,append:Gc});kd();md();document.__CE_hasRegistry=!0;var customElements=new N(O);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function od(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function pd(a){a=a.replace(qd,"").replace(rd,"");var b=sd,c=a,d=new od;d.start=0;d.end=c.length;for(var e=d,f=0,h=c.length;f<h;f++)if("{"===c[f]){e.rules||(e.rules=[]);var g=e,k=g.rules[g.rules.length-1]||null;e=new od;e.start=f+1;e.parent=g;e.previous=k;g.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function sd(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=td(c),c=c.replace(ud," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=vd:c.match(wd)&&(a.type=xd,a.keyframesName=a.selector.split(ud).pop()):a.type=0===c.indexOf("--")?yd:zd);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)sd(f,
b);return a}function td(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function Ad(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var h=e.length,g;f<h&&(g=e[f]);f++)d=Ad(g,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(Bd,"").replace(Cd,""),b=b.replace(Dd,"").replace(Ed,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var zd=1,xd=7,vd=4,yd=1E3,qd=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,rd=/@import[^;]*;/gim,Bd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Cd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Dd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Ed=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,wd=/^@[^\s]*keyframes/,ud=/\s+/g;var Q=!(window.ShadyDOM&&window.ShadyDOM.inUse),Fd;function Gd(a){Fd=a&&a.shimcssproperties?!1:Q||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?Fd=window.ShadyCSS.nativeCss:window.ShadyCSS?(Gd(window.ShadyCSS),window.ShadyCSS=void 0):Gd(window.WebComponents&&window.WebComponents.flags);var R=Fd;var Hd=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Id=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,Jd=/(--[\w-]+)\s*([:,;)]|$)/gi,Kd=/(animation\s*:)|(animation-name\s*:)/,Ld=/@media\s(.*)/,Md=/\{[^}]*\}/g;var Nd=new Set;function S(a,b){if(!a)return"";"string"===typeof a&&(a=pd(a));b&&T(a,b);return Ad(a,R)}function Od(a){!a.__cssRules&&a.textContent&&(a.__cssRules=pd(a.textContent));return a.__cssRules||null}function Pd(a){return!!a.parent&&a.parent.type===xd}function T(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===vd){var h=a.selector.match(Ld);h&&(window.matchMedia(h[1]).matches||(e=!0))}f===zd?b(a):c&&f===xd?c(a):f===yd&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var g;e<f&&(g=a[e]);e++)T(g,b,c,d)}}}
function Qd(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;Rd(e,c,d);return e}var U=null;function Rd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);U?a.compareDocumentPosition(U)===Node.DOCUMENT_POSITION_PRECEDING&&(U=a):U=a}
function Sd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=Sd(a.substring(e+1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function Td(a,b){Q?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function V(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,H:c}};function Ud(){}function Vd(a,b,c){var d=W;a.__styleScoped?a.__styleScoped=null:Wd(d,a,b||"",c)}function Wd(a,b,c,d){b.nodeType===Node.ELEMENT_NODE&&Xd(b,c,d);if(b="template"===b.localName?(b.content||b.Ja).childNodes:b.children||b.childNodes)for(var e=0;e<b.length;e++)Wd(a,b[e],c,d)}
function Xd(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(Yd);c?d&&(b=d.replace("style-scope","").replace(b,""),Td(a,b)):Td(a,(d?d+" ":"")+"style-scope "+b)}}function Zd(a,b,c){var d=W,e=a.__cssBuild;Q||"shady"===e?b=S(b,c):(a=V(a),b=$d(d,b,a.is,a.H,c)+"\n\n");return b.trim()}
function $d(a,b,c,d,e){var f=ae(c,d);c=c?be+c:"";return S(b,function(b){b.c||(b.selector=b.j=ce(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function ae(a,b){return b?"[is="+a+"]":a}function ce(a,b,c,d,e){var f=b.selector.split(de);if(!Pd(b)){b=0;for(var h=f.length,g;b<h&&(g=f[b]);b++)f[b]=c.call(a,g,d,e)}return f.join(de)}function ee(a){return a.replace(fe,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
Ud.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=fe.test(a);e&&(a=a.replace(fe,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=ee(a));a=a.replace(ge,he+" $1");a=a.replace(ie,function(a,e,g){d||(a=je(g,e,b,c),d=d||a.stop,e=a.sa,g=a.value);return e+g});e&&(a=ee(a));return a};
function je(a,b,c,d){var e=a.indexOf(ke);0<=a.indexOf(he)?a=le(a,d):0!==e&&(a=c?me(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(ne,function(a,b){return" > "+b}))}a=a.replace(oe,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,sa:b,stop:f}}function me(a,b){a=a.split(pe);a[0]+=b;return a.join(pe)}
function le(a,b){var c=a.match(qe);return(c=c&&c[2].trim()||"")?c[0].match(re)?a.replace(qe,function(a,c,f){return b+f}):c.split(re)[0]===b?c:se:a.replace(he,b)}function te(a){a.selector===ue&&(a.selector="html")}Ud.prototype.c=function(a){return a.match(ke)?this.b(a,ve):me(a.trim(),ve)};p.Object.defineProperties(Ud.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var fe=/:(nth[-\w]+)\(([^)]+)\)/,ve=":not(.style-scope)",de=",",ie=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,re=/[[.:#*]/,he=":host",ue=":root",ke="::slotted",ge=new RegExp("^("+ke+")"),qe=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ne=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,oe=/(.*):dir\((?:(ltr|rtl))\)/,be=".",pe=":",Yd="class",se="should_not_match",W=new Ud;function we(a,b,c,d){this.s=a||null;this.b=b||null;this.Z=c||[];this.A=null;this.H=d||"";this.a=this.m=this.u=null}function X(a){return a?a.__styleInfo:null}function xe(a,b){return a.__styleInfo=b}we.prototype.c=function(){return this.s};we.prototype._getStyleRules=we.prototype.c;function ye(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var ze=navigator.userAgent.match("Trident");function Ae(){}function Be(a){var b={},c=[],d=0;T(a,function(a){Ce(a);a.index=d++;a=a.h.cssText;for(var c;c=Jd.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function Ce(a){if(!a.h){var b={},c={};De(a,c)&&(b.o=c,a.rules=null);b.cssText=a.parsedCssText.replace(Md,"").replace(Hd,"");a.h=b}}function De(a,b){var c=a.h;if(c){if(c.o)return Object.assign(b,c.o),!0}else{c=a.parsedCssText;for(var d;a=Hd.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function Ee(a,b,c){b&&(b=0<=b.indexOf(";")?Fe(a,b,c):Sd(b,function(b,e,f,h){if(!e)return b+h;(e=Ee(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=Ee(a,c[f]||f,c)||f;return b+(e||"")+h}));return b&&b.trim()||""}
function Fe(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){Id.lastIndex=0;if(f=Id.exec(e))e=Ee(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var h=e.substring(f);h=h.trim();h=Ee(a,h,c)||h;e=e.substring(0,f)+h}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Ge(a,b){var c={},d=[];T(a,function(a){a.h||Ce(a);var e=a.j||a.parsedSelector;b&&a.h.o&&e&&ye.call(b,e)&&(De(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{o:c,key:d}}
function He(a,b,c,d){b.h||Ce(b);if(b.h.o){var e=V(a);a=e.is;e=e.H;e=a?ae(a,e):"html";var f=b.parsedSelector,h=":host > *"===f||"html"===f,g=0===f.indexOf(":host")&&!h;"shady"===c&&(h=f===e+" > *."+e||-1!==f.indexOf("html"),g=!h&&0===f.indexOf(e));"shadow"===c&&(h=":host > *"===f||"html"===f,g=g&&!h);if(h||g)c=e,g&&(b.j||(b.j=ce(W,b,W.b,a?be+a:"",e)),c=b.j||e),d({Aa:c,wa:g,Ka:h})}}
function Ie(a,b){var c={},d={},e=b&&b.__cssBuild;T(b,function(b){He(a,b,e,function(e){ye.call(a.g||a,e.Aa)&&(e.wa?De(b,c):De(b,d))})},null,!0);return{za:d,va:c}}
function Je(a,b,c,d){var e=V(b),f=ae(e.is,e.H),h=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=X(b).s;var g=Ke(e,d);return Zd(b,e,function(b){var e="";b.h||Ce(b);b.h.cssText&&(e=Fe(a,b.h.cssText,c));b.cssText=e;if(!Q&&!Pd(b)&&b.cssText){var k=e=b.cssText;null==b.da&&(b.da=Kd.test(e));if(b.da)if(null==b.M){b.M=[];for(var q in g)k=g[q],k=k(e),e!==k&&(e=k,b.M.push(q))}else{for(q=0;q<b.M.length;++q)k=g[b.M[q]],e=k(e);k=e}b.cssText=k;b.j=b.j||b.selector;e="."+d;
q=b.j.split(",");k=0;for(var H=q.length,P;k<H&&(P=q[k]);k++)q[k]=P.match(h)?P.replace(f,e):e+" "+P;b.selector=q.join(",")}})}function Ke(a,b){a=a.b;var c={};if(!Q&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,h=b;f.g=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+h;f.j=f.j||f.selector;f.selector=f.j.replace(f.keyframesName,f.a);c[e.keyframesName]=Le(e)}return c}function Le(a){return function(b){return b.replace(a.g,a.a)}}
function Me(a,b){var c=Ne,d=Od(a);a.textContent=S(d,function(a){var d=a.cssText=a.parsedCssText;a.h&&a.h.cssText&&(d=d.replace(Bd,"").replace(Cd,""),a.cssText=Fe(c,d,b))})}p.Object.defineProperties(Ae.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var Ne=new Ae;var Oe={},Pe=window.customElements;if(Pe&&!Q){var Qe=Pe.define;Pe.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(U?U.nextSibling:null)||e.firstChild);U=d;Oe[a]=d;Qe.call(Pe,a,b,c)}};function Re(){this.cache={}}Re.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({o:b,styleElement:c,m:d});100<e.length&&e.shift();this.cache[a]=e};Re.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var h=c[f];if(e.o[h]!==b[h]){f=!1;break a}}f=!0}if(f)return e}};function Se(){}
function Te(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var h=e;var g=[];h.classList?g=Array.from(h.classList):h instanceof window.SVGElement&&h.hasAttribute("class")&&(g=h.getAttribute("class").split(/\s+/));h=g;g=h.indexOf(W.a);if((h=-1<g?h[g+1]:"")&&f===e.ownerDocument)Vd(e,h,!0);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host)){f=V(f).is;g=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+W.a+")");for(var k=0;k<g.length;k++){var l=g[k],m=l.getRootNode().host;m&&(m=V(m).is,Xd(l,m))}f!==h&&(h&&Vd(e,h,!0),Vd(e,f))}}}}}
if(!Q){var Ue=new MutationObserver(Te),Ve=function(a){Ue.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Ve(document);else{var We=function(){Ve(document.body)};window.HTMLImports?window.HTMLImports.whenReady(We):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){We();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else We()})}Se=function(){Te(Ue.takeRecords())}}
var Xe=Se;var Ye={};var Ze=Promise.resolve();function $e(a){if(a=Ye[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function af(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function bf(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.a||(a.a=!0,Ze.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.a=!1}))};var cf=new Re;function Y(){this.ca={};this.c=document.documentElement;var a=new od;a.rules=[];this.g=xe(this.c,new we(a));this.w=!1;this.b=this.a=null}n=Y.prototype;n.ha=function(){Xe()};n.ta=function(a){return Od(a)};n.Ca=function(a){return S(a)};
n.prepareTemplate=function(a,b,c){if(!a.b){a.b=!0;a.name=b;a.extends=c;Ye[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),h=0;h<f.length;h++){var g=f[h];if(g.hasAttribute("shady-unscoped")){if(!Q){var k=g.textContent;Nd.has(k)||(Nd.add(k),k=g.cloneNode(!0),document.head.appendChild(k));g.parentNode.removeChild(g)}}else e.push(g.textContent),g.parentNode.removeChild(g)}e=e.join("").trim();c={is:b,extends:c,Ha:d};
Q||Vd(a.content,b);df(this);f=Id.test(e)||Hd.test(e);Id.lastIndex=0;Hd.lastIndex=0;e=pd(e);f&&R&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.c=d;d=[];R||(d=Be(a._styleAst));if(!d.length||R)e=Q?a.content:null,b=Oe[b],f=Zd(c,a._styleAst),b=f.length?Qd(f,c.is,e,b):void 0,a.ba=b;a.qa=d}};
function ef(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.fa(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.w)&&a.flushCustomStyles()})})}function df(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=$e);ef(a)}
n.flushCustomStyles=function(){df(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(R)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&R&&this.a){var d=Od(c);df(this);this.a.transformRules(d);c.textContent=S(d)}}else for(ff(this,this.c,this.g),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&Me(c,this.g.u);this.b.enqueued=!1;this.w&&!R&&this.styleDocument()}}};
n.styleElement=function(a,b){var c=V(a).is,d=X(a);if(!d){var e=V(a);d=e.is;e=e.H;var f=Oe[d];d=Ye[d];if(d){var h=d._styleAst;var g=d.qa}d=xe(a,new we(h,f,g,e))}a!==this.c&&(this.w=!0);b&&(d.A=d.A||{},Object.assign(d.A,b));if(R){if(d.A){b=d.A;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=Ye[c])||a===this.c)&&k&&k.ba&&!af(k)){if(af(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)df(this),this.a&&this.a.transformRules(k._styleAst,c),k.ba.textContent=
Zd(a,d.s),bf(k);Q&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=Zd(a,d.s));d.s=k._styleAst}}else if(ff(this,a,d),d.Z&&d.Z.length){c=d;k=V(a).is;d=(b=cf.fetch(k,c.u,c.Z))?b.styleElement:null;h=c.m;(g=b&&b.m)||(g=this.ca[k]=(this.ca[k]||0)+1,g=k+"-"+g);c.m=g;g=c.m;e=Ne;e=d?d.textContent||"":Je(e,a,c.u,g);f=X(a);var l=f.a;l&&!Q&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));Q?f.a?(f.a.textContent=e,d=f.a):e&&(d=Qd(e,g,a.shadowRoot,f.b)):d?d.parentNode||(ze&&
-1<e.indexOf("@media")&&(d.textContent=e),Rd(d,null,f.b)):e&&(d=Qd(e,g,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);g=d;Q||(d=c.m,f=e=a.getAttribute("class")||"",h&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+h+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&Td(a,f));b||cf.store(k,c.u,g,c.m)}};function gf(a,b){return(b=b.getRootNode().host)?X(b)?b:gf(a,b):a.c}
function ff(a,b,c){a=gf(a,b);var d=X(a);a=Object.create(d.u||null);var e=Ie(b,c.s);b=Ge(d.s,b).o;Object.assign(a,e.va,b,e.za);b=c.A;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=Ne;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=Ee(f,a[d],a);c.u=a}n.styleDocument=function(a){this.styleSubtree(this.c,a)};
n.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};n.fa=function(a){var b=this,c=Od(a);T(c,function(a){if(Q)te(a);else{var c=W;a.selector=a.parsedSelector;te(a);a.selector=a.j=ce(c,a,c.c,void 0,void 0)}R&&(df(b),b.a&&b.a.transformRule(a))});R?a.textContent=S(c):this.g.s.rules.push(c)};
n.getComputedStyleValue=function(a,b){var c;R||(c=(X(a)||X(gf(this,a))).u[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};n.Ba=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===W.a){c=d[e+1];break}}}c&&b.push(W.a,c);R||(c=X(a))&&c.m&&b.push(Ne.a,c.m);Td(a,b.join(" "))};n.ra=function(a){return X(a)};Y.prototype.flush=Y.prototype.ha;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Ba;Y.prototype._styleInfoForNode=Y.prototype.ra;Y.prototype.transformCustomStyleForDocument=Y.prototype.fa;Y.prototype.getStyleAst=Y.prototype.ta;Y.prototype.styleAstToString=Y.prototype.Ca;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return Q}},nativeCss:{get:function(){return R}}});var Z=new Y,hf,jf;window.ShadyCSS&&(hf=window.ShadyCSS.ApplyShim,jf=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:R,nativeShadow:Q};hf&&(window.ShadyCSS.ApplyShim=hf);
jf&&(window.ShadyCSS.CustomStyleInterface=jf);var kf=window.document;window.WebComponents=window.WebComponents||{};function lf(){requestAnimationFrame(function(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})}function mf(){lf();kf.removeEventListener("readystatechange",mf)}"loading"!==kf.readyState?lf():kf.addEventListener("readystatechange",mf);}).call(this);

//# sourceMappingURL=webcomponents-sd-ce.js.map
