(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var p,q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function da(){da=function(){};q.Symbol||(q.Symbol=ea)}var ea=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function fa(){da();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(this)}});fa=function(){}}function ha(a){var b=0;return ia(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ia(a){fa();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}function ja(a){fa();var b=a[Symbol.iterator];return b?b.call(a):ha(a)}
function ka(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();return a.defaultPrevented}()){var a=Event.prototype.preventDefault;Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.CustomEvent||b&&"function"!==typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");
c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=window.Event.prototype;if(!window.Event||b&&"function"!==typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c)for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}if(!window.MouseEvent||b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=function(a,
b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,b.view||window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=
a,m=e,n=Object.getOwnPropertyNames(m),t=0;t<n.length;t++)e=n[t],f[e]=m[e];return a})})(window.WebComponents);(function(){function a(){}function b(a,b){if(!a.childNodes.length)return[];switch(a.nodeType){case Node.DOCUMENT_NODE:return t.call(a,b);case Node.DOCUMENT_FRAGMENT_NODE:return B.call(a,b);default:return n.call(a,b)}}var c="undefined"===typeof HTMLTemplateElement,d=!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment),e=!1;/Trident/.test(navigator.userAgent)&&function(){function a(a,b){if(a instanceof DocumentFragment)for(var d;d=a.firstChild;)c.call(this,d,b);else c.call(this,
a,b);return a}e=!0;var b=Node.prototype.cloneNode;Node.prototype.cloneNode=function(a){a=b.call(this,a);this instanceof DocumentFragment&&(a.__proto__=DocumentFragment.prototype);return a};DocumentFragment.prototype.querySelectorAll=HTMLElement.prototype.querySelectorAll;DocumentFragment.prototype.querySelector=HTMLElement.prototype.querySelector;Object.defineProperties(DocumentFragment.prototype,{nodeType:{get:function(){return Node.DOCUMENT_FRAGMENT_NODE},configurable:!0},localName:{get:function(){},
configurable:!0},nodeName:{get:function(){return"#document-fragment"},configurable:!0}});var c=Node.prototype.insertBefore;Node.prototype.insertBefore=a;var d=Node.prototype.appendChild;Node.prototype.appendChild=function(b){b instanceof DocumentFragment?a.call(this,b,null):d.call(this,b);return b};var f=Node.prototype.removeChild,h=Node.prototype.replaceChild;Node.prototype.replaceChild=function(b,c){b instanceof DocumentFragment?(a.call(this,b,c),f.call(this,c)):h.call(this,b,c);return c};Document.prototype.createDocumentFragment=
function(){var a=this.createElement("df");a.__proto__=DocumentFragment.prototype;return a};var g=Document.prototype.importNode;Document.prototype.importNode=function(a,b){b=g.call(this,a,b||!1);a instanceof DocumentFragment&&(b.__proto__=DocumentFragment.prototype);return b}}();var f=Node.prototype.cloneNode,h=Document.prototype.createElement,g=Document.prototype.importNode,k=Node.prototype.removeChild,l=Node.prototype.appendChild,m=Node.prototype.replaceChild,n=Element.prototype.querySelectorAll,
t=Document.prototype.querySelectorAll,B=DocumentFragment.prototype.querySelectorAll,fb=function(){if(!c){var a=document.createElement("template"),b=document.createElement("template");b.content.appendChild(document.createElement("div"));a.content.appendChild(b);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||d}}();if(c){var J=document.implementation.createHTMLDocument("template"),Da=!0,W=document.createElement("style");W.textContent="template{display:none;}";
var Ea=document.head;Ea.insertBefore(W,Ea.firstElementChild);a.prototype=Object.create(HTMLElement.prototype);var y=!document.createElement("div").hasOwnProperty("innerHTML");a.D=function(b){if(!b.content&&b.namespaceURI===document.documentElement.namespaceURI){b.content=J.createDocumentFragment();for(var c;c=b.firstChild;)l.call(b.content,c);if(y)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a.ca(this,b)},Da)try{na(b),ba(b)}catch(Mg){Da=!1}a.I(b.content)}};var na=function(b){Object.defineProperty(b,
"innerHTML",{get:function(){return gb(this)},set:function(b){J.body.innerHTML=b;for(a.I(J);this.content.firstChild;)k.call(this.content,this.content.firstChild);for(;J.body.firstChild;)l.call(this.content,J.body.firstChild)},configurable:!0})},ba=function(a){Object.defineProperty(a,"outerHTML",{get:function(){return"<template>"+this.innerHTML+"</template>"},set:function(a){if(this.parentNode){J.body.innerHTML=a;for(a=this.ownerDocument.createDocumentFragment();J.body.firstChild;)l.call(a,J.body.firstChild);
m.call(this.parentNode,a,this)}else throw Error("Failed to set the 'outerHTML' property on 'Element': This element has no parent node.");},configurable:!0})};na(a.prototype);ba(a.prototype);a.I=function(c){c=b(c,"template");for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)a.D(f)};document.addEventListener("DOMContentLoaded",function(){a.I(document)});Document.prototype.createElement=function(){var b=h.apply(this,arguments);"template"===b.localName&&a.D(b);return b};var oa=/[&\u00A0"]/g,X=/[&\u00A0<>]/g,
ca=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}};W=function(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b};var He=W("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),pa=W("style script xmp iframe noembed noframes plaintext noscript".split(" ")),gb=function(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,
h;e<f&&(h=d[e]);e++){a:{var g=h;var k=a;var l=b;switch(g.nodeType){case Node.ELEMENT_NODE:for(var m=g.localName,n="<"+m,qa=g.attributes,Fa=0;k=qa[Fa];Fa++)n+=" "+k.name+'="'+k.value.replace(oa,ca)+'"';n+=">";g=He[m]?n:n+gb(g,l)+"</"+m+">";break a;case Node.TEXT_NODE:g=g.data;g=k&&pa[k.localName]?g:g.replace(X,ca);break a;case Node.COMMENT_NODE:g="\x3c!--"+g.data+"--\x3e";break a;default:throw window.console.error(g),Error("not implemented");}}c+=g}return c}}if(c||fb){a.ca=function(a,b){var c=f.call(a,
!1);this.D&&this.D(c);b&&(l.call(c.content,f.call(a.content,!0)),qa(c.content,a.content));return c};var qa=function(c,d){if(d.querySelectorAll&&(d=b(d,"template"),0!==d.length)){c=b(c,"template");for(var e=0,f=c.length,h,g;e<f;e++)g=d[e],h=c[e],a&&a.D&&a.D(g),m.call(h.parentNode,Fa.call(g,!0),h)}},Fa=Node.prototype.cloneNode=function(b){if(!e&&d&&this instanceof DocumentFragment)if(b)var c=Ie.call(this.ownerDocument,this,!0);else return this.ownerDocument.createDocumentFragment();else c=this.nodeType===
Node.ELEMENT_NODE&&"template"===this.localName&&this.namespaceURI==document.documentElement.namespaceURI?a.ca(this,b):f.call(this,b);b&&qa(c,this);return c},Ie=Document.prototype.importNode=function(c,d){d=d||!1;if("template"===c.localName)return a.ca(c,d);var e=g.call(this,c,d);if(d){qa(e,c);c=b(e,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"]');for(var f,k=0;k<c.length;k++){f=c[k];d=h.call(document,"script");d.textContent=f.textContent;for(var l=f.attributes,
ca=0,pa;ca<l.length;ca++)pa=l[ca],d.setAttribute(pa.name,pa.value);m.call(f.parentNode,d,f)}}return e}}c&&(window.HTMLTemplateElement=a)})();var la=Array.isArray?Array.isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)};var ma=0,ra,sa="undefined"!==typeof window?window:void 0,ta=sa||{},ua=ta.MutationObserver||ta.WebKitMutationObserver,va="undefined"!==typeof Uint8ClampedArray&&"undefined"!==typeof importScripts&&"undefined"!==typeof MessageChannel;function wa(){return"undefined"!==typeof ra?function(){ra(xa)}:ya()}function za(){var a=0,b=new ua(xa),c=document.createTextNode("");b.observe(c,{characterData:!0});return function(){c.data=a=++a%2}}
function Aa(){var a=new MessageChannel;a.port1.onmessage=xa;return function(){return a.port2.postMessage(0)}}function ya(){var a=setTimeout;return function(){return a(xa,1)}}var Ba=Array(1E3);function xa(){for(var a=0;a<ma;a+=2)(0,Ba[a])(Ba[a+1]),Ba[a]=void 0,Ba[a+1]=void 0;ma=0}var Ca,Ga;
if("undefined"===typeof self&&"undefined"!==typeof process&&"[object process]"==={}.toString.call(process))Ga=function(){return process.jb(xa)};else{var Ha;if(ua)Ha=za();else{var Ia;if(va)Ia=Aa();else{var Ja;if(void 0===sa&&"function"===typeof require)try{var Ka=require("vertx");ra=Ka.mb||Ka.lb;Ja=wa()}catch(a){Ja=ya()}else Ja=ya();Ia=Ja}Ha=Ia}Ga=Ha}Ca=Ga;function La(a,b){Ba[ma]=a;Ba[ma+1]=b;ma+=2;2===ma&&Ca()};function Ma(a,b){var c=this,d=new this.constructor(Na);void 0===d[Oa]&&Pa(d);var e=c.g;if(e){var f=arguments[e-1];La(function(){return Qa(e,d,f,c.f)})}else Ra(c,d,a,b);return d};function Sa(a){if(a&&"object"===typeof a&&a.constructor===this)return a;var b=new this(Na);Ta(b,a);return b};var Oa=Math.random().toString(36).substring(16);function Na(){}var Va=new Ua;function Wa(a){try{return a.then}catch(b){return Va.error=b,Va}}function Xa(a,b,c,d){try{a.call(b,c,d)}catch(e){return e}}function Ya(a,b,c){La(function(a){var d=!1,f=Xa(c,b,function(c){d||(d=!0,b!==c?Ta(a,c):r(a,c))},function(b){d||(d=!0,u(a,b))});!d&&f&&(d=!0,u(a,f))},a)}function Za(a,b){1===b.g?r(a,b.f):2===b.g?u(a,b.f):Ra(b,void 0,function(b){return Ta(a,b)},function(b){return u(a,b)})}
function $a(a,b,c){b.constructor===a.constructor&&c===Ma&&b.constructor.resolve===Sa?Za(a,b):c===Va?(u(a,Va.error),Va.error=null):void 0===c?r(a,b):"function"===typeof c?Ya(a,b,c):r(a,b)}function Ta(a,b){if(a===b)u(a,new TypeError("You cannot resolve a promise with itself"));else{var c=typeof b;null===b||"object"!==c&&"function"!==c?r(a,b):$a(a,b,Wa(b))}}function ab(a){a.na&&a.na(a.f);bb(a)}function r(a,b){void 0===a.g&&(a.f=b,a.g=1,0!==a.H.length&&La(bb,a))}
function u(a,b){void 0===a.g&&(a.g=2,a.f=b,La(ab,a))}function Ra(a,b,c,d){var e=a.H,f=e.length;a.na=null;e[f]=b;e[f+1]=c;e[f+2]=d;0===f&&a.g&&La(bb,a)}function bb(a){var b=a.H,c=a.g;if(0!==b.length){for(var d,e,f=a.f,h=0;h<b.length;h+=3)d=b[h],e=b[h+c],d?Qa(c,d,e,f):e(f);a.H.length=0}}function Ua(){this.error=null}var cb=new Ua;
function Qa(a,b,c,d){var e="function"===typeof c;if(e){try{var f=c(d)}catch(l){cb.error=l,f=cb}if(f===cb){var h=!0;var g=f.error;f.error=null}else var k=!0;if(b===f){u(b,new TypeError("A promises callback cannot return that same promise."));return}}else f=d,k=!0;void 0===b.g&&(e&&k?Ta(b,f):h?u(b,g):1===a?r(b,f):2===a&&u(b,f))}function db(a,b){try{b(function(b){Ta(a,b)},function(b){u(a,b)})}catch(c){u(a,c)}}var eb=0;function Pa(a){a[Oa]=eb++;a.g=void 0;a.f=void 0;a.H=[]};function hb(a,b){this.Ea=a;this.A=new a(Na);this.A[Oa]||Pa(this.A);if(la(b))if(this.R=this.length=b.length,this.f=Array(this.length),0===this.length)r(this.A,this.f);else{this.length=this.length||0;for(a=0;void 0===this.g&&a<b.length;a++)ib(this,b[a],a);0===this.R&&r(this.A,this.f)}else u(this.A,Error("Array Methods must be provided an Array"))}
function ib(a,b,c){var d=a.Ea,e=d.resolve;e===Sa?(e=Wa(b),e===Ma&&void 0!==b.g?jb(a,b.g,c,b.f):"function"!==typeof e?(a.R--,a.f[c]=b):d===v?(d=new d(Na),$a(d,b,e),kb(a,d,c)):kb(a,new d(function(a){return a(b)}),c)):kb(a,e(b),c)}function jb(a,b,c,d){var e=a.A;void 0===e.g&&(a.R--,2===b?u(e,d):a.f[c]=d);0===a.R&&r(e,a.f)}function kb(a,b,c){Ra(b,void 0,function(b){return jb(a,1,c,b)},function(b){return jb(a,2,c,b)})};function lb(a){return(new hb(this,a)).A};function mb(a){var b=this;return la(a)?new b(function(c,d){for(var e=a.length,f=0;f<e;f++)b.resolve(a[f]).then(c,d)}):new b(function(a,b){return b(new TypeError("You must pass an array to race."))})};function nb(a){var b=new this(Na);u(b,a);return b};function v(a){this[Oa]=eb++;this.f=this.g=void 0;this.H=[];if(Na!==a){if("function"!==typeof a)throw new TypeError("You must pass a resolver function as the first argument to the promise constructor");if(this instanceof v)db(this,a);else throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");}}v.prototype={constructor:v,then:Ma,a:function(a){return this.then(null,a)}};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
window.Promise||(window.Promise=v,v.prototype["catch"]=v.prototype.a,v.prototype.then=v.prototype.then,v.all=lb,v.race=mb,v.resolve=Sa,v.reject=nb);(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(B)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!g(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=m(document,"link[rel=import]:not([import-dependency])"),
c=b.length;c?n(b,function(b){return h(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function h(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);ba&&"style"===a.localName||a.addEventListener("error",c)}}function g(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.a={};this.b=0;this.c=new MutationObserver(function(b){return a.Ra(b)});this.c.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a){n(m(a,"template"),function(a){n(m(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"]'),
function(a){var b=document.createElement("script");n(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});l(a.content)})}function m(a,b){return a.childNodes.length?a.querySelectorAll(b):fb}function n(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var t=document.createElement("link"),B="import"in t,fb=t.querySelectorAll("*"),J=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",
{get:function(){return J||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Da=/(url\()([^)]*)(\))/g,W=/(@import[\s]+(?!url\())([^;]*)(;)/g,Ea=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,y={La:function(a,b){a.href&&a.setAttribute("href",y.X(a.getAttribute("href"),b));a.src&&a.setAttribute("src",y.X(a.getAttribute("src"),b));if("style"===a.localName){var c=y.ta(a.textContent,b,Da);a.textContent=y.ta(c,b,W)}},ta:function(a,b,c){return a.replace(c,
function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=y.X(a,b));return c+"'"+a+"'"+e})},X:function(a,b){if(void 0===y.ba){y.ba=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";y.ba="http://a/c%20d"===c.href}catch(gb){}}if(y.ba)return(new URL(a,b)).href;c=y.Ba;c||(c=document.implementation.createHTMLDocument("temp"),y.Ba=c,c.ma=c.createElement("base"),c.head.appendChild(c.ma),c.la=c.createElement("a"));c.ma.href=b;c.la.href=a;return c.la.href||a}},na={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=
a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,na.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},ba=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);
k.prototype.loadImports=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){return b.s(a)})};k.prototype.s=function(a){var b=this,c=a.href;if(void 0!==this.a[c]){var d=this.a[c];d&&d.__loaded&&(a.__import=d,this.h(a))}else this.b++,this.a[c]="pending",na.load(c,function(a,d){a=b.Sa(a,d||c);b.a[c]=a;b.b--;b.loadImports(a);b.K()},function(){b.a[c]=null;b.b--;b.K()})};k.prototype.Sa=function(a,b){if(!a)return document.createDocumentFragment();ba&&(a=a.replace(Ea,function(a,b,c){return-1===
a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,l(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=y.X(c.getAttribute("href"),b),c.removeAttribute("href");c=m(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"]');
var d=0;n(c,function(a){h(a);y.La(a,b);a.setAttribute("import-dependency","");"script"===a.localName&&!a.src&&a.textContent&&(a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n"))),a.textContent="",d++)});return a};k.prototype.K=function(){var a=this;if(!this.b){this.c.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.loadImports(document),a.b||(a.c.observe(document.head,{childList:!0,subtree:!0}),
a.Pa()))};this.Ua(function(){c=!0;d()});this.Ta(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=m(a,"link[rel=import]");n(a,function(a){var c=b.a[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.a[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),a.appendChild(c))})};k.prototype.Ta=function(a){function b(e){if(e<d){var f=c[e],g=document.createElement("script");f.removeAttribute("import-dependency");n(f.attributes,function(a){return g.setAttribute(a.name,
a.value)});J=g;f.parentNode.replaceChild(g,f);h(g,function(){J=null;b(e+1)})}else a()}var c=m(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.Ua=function(a){var b=m(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=ba&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");n(b,function(b){h(b,function(){b.removeAttribute("import-dependency");0===--d&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);
f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.Pa=function(){var a=this,b=m(document,"link[rel=import]");n(b,function(b){return a.h(b)},!0)};k.prototype.h=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(b(a.import?"load":"error",{bubbles:!1,
cancelable:!1,detail:void 0})))};k.prototype.Ra=function(a){var b=this;n(a,function(a){return n(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(g(a)?b.s(a):b.loadImports(a))})})};var oa=null;if(B)t=m(document,"link[rel=import]"),n(t,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),t=function(a){a=a.target;g(a)&&(a.__loaded=!0)},document.addEventListener("load",t,!0),document.addEventListener("error",t,!0);else{var X=Object.getOwnPropertyDescriptor(Node.prototype,
"baseURI");Object.defineProperty((!X||X.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=g(this)?this:c(this);return a?a.href:X&&X.get?X.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){oa=new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,
detail:void 0}))});a.useNative=B;a.whenReady=f;a.importForElement=c;a.loadImports=function(a){oa&&oa.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
window.WebComponents=window.WebComponents||{flags:{}};window.WebComponents.kb="https://github.com/Updater/webcomponentsjs";var ob=document.querySelector('script[src*="webcomponents-lite.js"]'),pb=/wc-(.+)/,w={};
if(!w.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var b;a[0]&&(b=a[0].match(pb))&&(w[b[1]]=a[1]||!0)});if(ob)for(var qb=0,rb;rb=ob.attributes[qb];qb++)"src"!==rb.name&&(w[rb.name]=rb.value||!0);if(w.log&&w.log.split){var sb=w.log.split(",");w.log={};sb.forEach(function(a){w.log[a]=!0})}else w.log={}}window.WebComponents.flags=w;var tb=w.shadydom;tb&&(window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=tb);var ub=w.register||w.ce;
ub&&window.customElements&&(window.customElements.forcePolyfill=ub);/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var x=window.ShadyDOM||{};x.Na=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var vb=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");x.L=!!(vb&&vb.configurable&&vb.get);x.sa=x.force||!x.Na;function wb(a){return a.__shady&&void 0!==a.__shady.firstChild}function z(a){return"ShadyRoot"===a.ya}function xb(a){a=a.getRootNode();if(z(a))return a}var yb=Element.prototype,zb=yb.matches||yb.matchesSelector||yb.mozMatchesSelector||yb.msMatchesSelector||yb.oMatchesSelector||yb.webkitMatchesSelector;
function Ab(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function Bb(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)Ab(a,c[d]);return a}function Cb(a,b){for(var c in b)a[c]=b[c]}var Db=document.createTextNode(""),Eb=0,Fb=[];(new MutationObserver(function(){for(;Fb.length;)try{Fb.shift()()}catch(a){throw Db.textContent=Eb++,a;}})).observe(Db,{characterData:!0});
function Gb(a){Fb.push(a);Db.textContent=Eb++}var Hb=!!document.contains;function Ib(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1};var Jb=[],Kb;function Lb(a){Kb||(Kb=!0,Gb(Mb));Jb.push(a)}function Mb(){Kb=!1;for(var a=!!Jb.length;Jb.length;)Jb.shift()();return a}Mb.list=Jb;function Nb(){this.a=!1;this.addedNodes=[];this.removedNodes=[];this.U=new Set}function Ob(a){a.a||(a.a=!0,Gb(function(){Pb(a)}))}function Pb(a){if(a.a){a.a=!1;var b=a.takeRecords();b.length&&a.U.forEach(function(a){a(b)})}}Nb.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Qb(a,b){a.__shady=a.__shady||{};a.__shady.M||(a.__shady.M=new Nb);a.__shady.M.U.add(b);var c=a.__shady.M;return{Ca:b,C:c,Ga:a,takeRecords:function(){return c.takeRecords()}}}function Rb(a){var b=a&&a.C;b&&(b.U.delete(a.Ca),b.U.size||(a.Ga.__shady.M=null))}
function Sb(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var A={},Tb=Element.prototype.insertBefore,Ub=Element.prototype.removeChild,Vb=Element.prototype.setAttribute,Wb=Element.prototype.removeAttribute,Xb=Element.prototype.cloneNode,Yb=Document.prototype.importNode,Zb=Element.prototype.addEventListener,$b=Element.prototype.removeEventListener,ac=Window.prototype.addEventListener,bc=Window.prototype.removeEventListener,cc=Element.prototype.dispatchEvent,dc=Element.prototype.querySelector,ec=Element.prototype.querySelectorAll,fc=Node.prototype.contains||
HTMLElement.prototype.contains;A.appendChild=Element.prototype.appendChild;A.insertBefore=Tb;A.removeChild=Ub;A.setAttribute=Vb;A.removeAttribute=Wb;A.cloneNode=Xb;A.importNode=Yb;A.addEventListener=Zb;A.removeEventListener=$b;A.bb=ac;A.cb=bc;A.dispatchEvent=cc;A.querySelector=dc;A.querySelectorAll=ec;A.contains=fc;var gc=/[&\u00A0"]/g,hc=/[&\u00A0<>]/g;function ic(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function jc(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var kc=jc("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),lc=jc("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function mc(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,h;e<f&&(h=d[e]);e++){a:{var g=h;var k=a;var l=b;switch(g.nodeType){case Node.ELEMENT_NODE:for(var m=g.localName,n="<"+m,t=g.attributes,B=0;k=t[B];B++)n+=" "+k.name+'="'+k.value.replace(gc,ic)+'"';n+=">";g=kc[m]?n:n+mc(g,l)+"</"+m+">";break a;case Node.TEXT_NODE:g=g.data;g=k&&lc[k.localName]?g:g.replace(hc,ic);break a;case Node.COMMENT_NODE:g="\x3c!--"+g.data+"--\x3e";break a;default:throw window.console.error(g),
Error("not implemented");}}c+=g}return c};var C={},D=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),E=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function nc(a){var b=[];D.currentNode=a;for(a=D.firstChild();a;)b.push(a),a=D.nextSibling();return b}C.parentNode=function(a){D.currentNode=a;return D.parentNode()};C.firstChild=function(a){D.currentNode=a;return D.firstChild()};C.lastChild=function(a){D.currentNode=a;return D.lastChild()};C.previousSibling=function(a){D.currentNode=a;return D.previousSibling()};
C.nextSibling=function(a){D.currentNode=a;return D.nextSibling()};C.childNodes=nc;C.parentElement=function(a){E.currentNode=a;return E.parentNode()};C.firstElementChild=function(a){E.currentNode=a;return E.firstChild()};C.lastElementChild=function(a){E.currentNode=a;return E.lastChild()};C.previousElementSibling=function(a){E.currentNode=a;return E.previousSibling()};C.nextElementSibling=function(a){E.currentNode=a;return E.nextSibling()};
C.children=function(a){var b=[];E.currentNode=a;for(a=E.firstChild();a;)b.push(a),a=E.nextSibling();return b};C.innerHTML=function(a){return mc(a,function(a){return nc(a)})};C.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var oc=Object.getOwnPropertyDescriptor(Element.prototype,"innerHTML")||Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML"),pc=document.implementation.createHTMLDocument("inert"),qc=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),rc={parentElement:{get:function(){var a=this.__shady&&this.__shady.parentNode;a&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:C.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=this.__shady&&this.__shady.parentNode;
return void 0!==a?a:C.parentNode(this)},configurable:!0},nextSibling:{get:function(){var a=this.__shady&&this.__shady.nextSibling;return void 0!==a?a:C.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=this.__shady&&this.__shady.previousSibling;return void 0!==a?a:C.previousSibling(this)},configurable:!0},className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0},nextElementSibling:{get:function(){if(this.__shady&&
void 0!==this.__shady.nextSibling){for(var a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return C.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){if(this.__shady&&void 0!==this.__shady.previousSibling){for(var a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return C.previousElementSibling(this)},configurable:!0}},sc={childNodes:{get:function(){if(wb(this)){if(!this.__shady.childNodes){this.__shady.childNodes=
[];for(var a=this.firstChild;a;a=a.nextSibling)this.__shady.childNodes.push(a)}var b=this.__shady.childNodes}else b=C.childNodes(this);b.item=function(a){return b[a]};return b},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=this.__shady&&this.__shady.firstChild;return void 0!==a?a:C.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=this.__shady&&this.__shady.lastChild;return void 0!==a?a:C.lastChild(this)},
configurable:!0},textContent:{get:function(){if(wb(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.textContent);return a.join("")}return C.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(;this.firstChild;)this.removeChild(this.firstChild);(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=
a}},configurable:!0},firstElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.firstChild){for(var a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return C.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){if(this.__shady&&void 0!==this.__shady.lastChild){for(var a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return C.lastElementChild(this)},configurable:!0},children:{get:function(){var a=wb(this)?
Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE}):C.children(this);a.item=function(b){return a[b]};return a},configurable:!0},innerHTML:{get:function(){var a="template"===this.localName?this.content:this;return wb(this)?mc(a):C.innerHTML(a)},set:function(a){for(var b="template"===this.localName?this.content:this;b.firstChild;)b.removeChild(b.firstChild);var c=this.localName;c&&"template"!==c||(c="div");c=pc.createElement(c);for(oc&&oc.set?oc.set.call(c,
a):c.innerHTML=a;c.firstChild;)b.appendChild(c.firstChild)},configurable:!0}},tc={shadowRoot:{get:function(){return this.__shady&&this.__shady.Wa||null},configurable:!0}},uc={activeElement:{get:function(){var a=qc&&qc.get?qc.get.call(document):x.L?void 0:document.activeElement;if(a&&a.nodeType){var b=!!z(this);if(this===document||b&&this.host!==a&&A.contains.call(this.host,a)){for(b=xb(a);b&&b!==this;)a=b.host,b=xb(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},
configurable:!0}};function F(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function G(a){F(a,rc);F(a,sc);F(a,uc)}var vc=x.L?function(){}:function(a){a.__shady&&a.__shady.za||(a.__shady=a.__shady||{},a.__shady.za=!0,F(a,rc,!0))},wc=x.L?function(){}:function(a){a.__shady&&a.__shady.xa||(a.__shady=a.__shady||{},a.__shady.xa=!0,F(a,sc,!0),F(a,tc,!0))};function xc(a,b,c){vc(a);c=c||null;a.__shady=a.__shady||{};b.__shady=b.__shady||{};c&&(c.__shady=c.__shady||{});a.__shady.previousSibling=c?c.__shady.previousSibling:b.lastChild;var d=a.__shady.previousSibling;d&&d.__shady&&(d.__shady.nextSibling=a);(d=a.__shady.nextSibling=c)&&d.__shady&&(d.__shady.previousSibling=a);a.__shady.parentNode=b;c?c===b.__shady.firstChild&&(b.__shady.firstChild=a):(b.__shady.lastChild=a,b.__shady.firstChild||(b.__shady.firstChild=a));b.__shady.childNodes=null}
function yc(a){if(!a.__shady||void 0===a.__shady.firstChild){a.__shady=a.__shady||{};a.__shady.firstChild=C.firstChild(a);a.__shady.lastChild=C.lastChild(a);wc(a);for(var b=a.__shady.childNodes=C.childNodes(a),c=0,d;c<b.length&&(d=b[c]);c++)d.__shady=d.__shady||{},d.__shady.parentNode=a,d.__shady.nextSibling=b[c+1]||null,d.__shady.previousSibling=b[c-1]||null,vc(d)}};function zc(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=c.__shady&&c.__shady.parentNode;if(void 0!==d&&d!==a||void 0===d&&C.parentNode(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Ac(b.parentNode,b);d=xb(a);var e;if(e=d)a:{if(!b.__noInsertionPoint){var f;"slot"===b.localName?f=[b]:
b.querySelectorAll&&(f=b.querySelectorAll("slot"));if(f&&f.length){e=f;break a}}e=void 0}(f=e)&&d.G.push.apply(d.G,[].concat(f instanceof Array?f:ka(ja(f))));d&&("slot"===a.localName||f)&&Bc(d);if(wb(a)){d=c;wc(a);a.__shady=a.__shady||{};void 0!==a.__shady.firstChild&&(a.__shady.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(e=0;e<f.length;e++)xc(f[e],a,d);b.__shady=b.__shady||{};d=void 0!==b.__shady.firstChild?null:void 0;b.__shady.firstChild=b.__shady.lastChild=
d;b.__shady.childNodes=d}else xc(b,a,d);if(Cc(a)){Bc(a.__shady.root);var h=!0}else a.__shady.root&&(h=!0)}h||(h=z(a)?a.host:a,c?(c=Dc(c),A.insertBefore.call(h,b,c)):A.appendChild.call(h,b));Ec(a,b);return b}
function Ac(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=xb(b);if(wb(a)){b.__shady=b.__shady||{};a.__shady=a.__shady||{};b===a.__shady.firstChild&&(a.__shady.firstChild=b.__shady.nextSibling);b===a.__shady.lastChild&&(a.__shady.lastChild=b.__shady.previousSibling);var d=b.__shady.previousSibling,e=b.__shady.nextSibling;d&&(d.__shady=d.__shady||{},d.__shady.nextSibling=e);e&&(e.__shady=e.__shady||{},e.__shady.previousSibling=d);b.__shady.parentNode=
b.__shady.previousSibling=b.__shady.nextSibling=void 0;void 0!==a.__shady.childNodes&&(a.__shady.childNodes=null);if(Cc(a)){Bc(a.__shady.root);var f=!0}}Fc(b);if(c){(d=a&&"slot"===a.localName)&&(f=!0);Gc(c);e=c.l;for(var h in e)for(var g=e[h],k=0;k<g.length;k++){var l=g[k];if(Ib(b,l)){g.splice(k,1);var m=c.o.indexOf(l);0<=m&&c.o.splice(m,1);k--;if(m=l.__shady.J)for(l=0;l<m.length;l++){var n=m[l],t=C.parentNode(n);t&&A.removeChild.call(t,n)}m=!0}}(m||d)&&Bc(c)}f||(f=z(a)?a.host:a,(!a.__shady.root&&
"slot"!==b.localName||f===C.parentNode(b))&&A.removeChild.call(f,b));Ec(a,null,b);return b}function Fc(a){if(a.__shady&&void 0!==a.__shady.ka)for(var b=a.childNodes,c=0,d=b.length,e;c<d&&(e=b[c]);c++)Fc(e);a.__shady&&(a.__shady.ka=void 0)}function Dc(a){var b=a;a&&"slot"===a.localName&&(b=(b=a.__shady&&a.__shady.J)&&b.length?b[0]:Dc(a.nextSibling));return b}function Cc(a){return(a=a&&a.__shady&&a.__shady.root)&&Hc(a)}
function Ic(a,b){if("slot"===b)a=a.parentNode,Cc(a)&&Bc(a.__shady.root);else if("slot"===a.localName&&"name"===b&&(b=xb(a))){var c=a.Aa,d=Jc(a);if(d!==c){c=b.l[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.l[d]||(b.l[d]=[]);c.push(a);1<c.length&&(b.l[d]=Kc(c))}Bc(b)}}function Ec(a,b,c){if(a=a.__shady&&a.__shady.M)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ob(a)}
function Lc(a){if(a&&a.nodeType){a.__shady=a.__shady||{};var b=a.__shady.ka;void 0===b&&(b=z(a)?a:(b=a.parentNode)?Lc(b):a,A.contains.call(document.documentElement,a)&&(a.__shady.ka=b));return b}}function Mc(a,b,c){var d=[];Nc(a.childNodes,b,c,d);return d}function Nc(a,b,c,d){for(var e=0,f=a.length,h;e<f&&(h=a[e]);e++){var g;if(g=h.nodeType===Node.ELEMENT_NODE){g=h;var k=b,l=c,m=d,n=k(g);n&&m.push(g);l&&l(n)?g=n:(Nc(g.childNodes,k,l,m),g=void 0)}if(g)break}}var Oc=null;
function Pc(a,b,c){Oc||(Oc=window.ShadyCSS&&window.ShadyCSS.ScopingShim);Oc&&"class"===b?Oc.setElementClass(a,c):(A.setAttribute.call(a,b,c),Ic(a,b))}function Qc(a,b){if(a.ownerDocument!==document)return A.importNode.call(document,a,b);var c=A.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Qc(a[b],!0),c.appendChild(d)}return c};var Rc="__eventWrappers"+Date.now(),Sc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,
dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0};function Tc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}
function Uc(a,b){if(!z)return a;a=Tc(a,!0);for(var c=0,d,e,f,h;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(h=a.indexOf(f),e=f),!z(f)||-1<h)return d}
var Vc={get composed(){!1!==this.isTrusted&&void 0===this.Z&&(this.Z=Sc[this.type]);return this.Z||!1},composedPath:function(){this.b||(this.b=Tc(this.__target,this.composed));return this.b},get target(){return Uc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.$)return null;this.c||(this.c=Tc(this.$,!0));return Uc(this.currentTarget,this.c)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.a=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
this.a=this.h=!0}};function Wc(a){function b(b,d){b=new a(b,d);b.Z=d&&!!d.composed;return b}Cb(b,a);b.prototype=a.prototype;return b}var Xc={focus:!0,blur:!0};function Yc(a){return a.__target!==a.target||a.$!==a.relatedTarget}function Zc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!Yc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.h);d++);}
function $c(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];Zc(a,d,"capture");if(a.a)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=d.__shady&&d.__shady.root;if(0===c||f&&f===e)if(Zc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.a)break}}
function ad(a,b,c,d,e,f){for(var h=0;h<a.length;h++){var g=a[h],k=g.type,l=g.capture,m=g.once,n=g.passive;if(b===g.node&&c===k&&d===l&&e===m&&f===n)return h}return-1}
function bd(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var h=!!c.passive}else e=!!c,h=f=!1;var g=c&&c.aa||this,k=b[Rc];if(k){if(-1<ad(k,g,a,e,f,h))return}else b[Rc]=[];k=function(e){f&&this.removeEventListener(a,b,c);e.__target||cd(e);if(g!==this){var h=Object.getOwnPropertyDescriptor(e,"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return g},
configurable:!0})}if(e.composed||-1<e.composedPath().indexOf(g))if(Yc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===g||g instanceof Window){var k="function"===d?b.call(g,e):b.handleEvent&&b.handleEvent(e);g!==this&&(h?(Object.defineProperty(e,"currentTarget",h),h=null):delete e.currentTarget);return k}};b[Rc].push({node:this,type:a,capture:e,once:f,passive:h,eb:k});Xc[a]?(this.__handlers=
this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(k)):(this instanceof Window?A.bb:A.addEventListener).call(this,a,k,c)}}}
function dd(a,b,c){if(b){if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var h=c&&c.aa||this,g=void 0;var k=null;try{k=b[Rc]}catch(l){}k&&(e=ad(k,h,a,d,e,f),-1<e&&(g=k.splice(e,1)[0].eb,k.length||(b[Rc]=void 0)));(this instanceof Window?A.cb:A.removeEventListener).call(this,a,g||b,c);g&&Xc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],g=a.indexOf(g),-1<g&&a.splice(g,1))}}
function ed(){for(var a in Xc)window.addEventListener(a,function(a){a.__target||(cd(a),$c(a))},!0)}function cd(a){a.__target=a.target;a.$=a.relatedTarget;if(x.L){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.gb=b;Ab(c,Vc);b.__patchProto=c}a.__proto__=b.__patchProto}else Ab(a,Vc)}var fd=Wc(window.Event),gd=Wc(window.CustomEvent),hd=Wc(window.MouseEvent);function id(a,b){return{index:a,N:[],T:b}}
function jd(a,b,c,d){var e=0,f=0,h=0,g=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(h=0;h<k;h++)if(a[h]!==c[h])break a;h=k}if(b==a.length&&d==c.length){g=a.length;for(var l=c.length,m=0;m<k-h&&kd(a[--g],c[--l]);)m++;g=m}e+=h;f+=h;b-=g;d-=g;if(0==b-e&&0==d-f)return[];if(e==b){for(b=id(e,0);f<d;)b.N.push(c[f++]);return[b]}if(f==d)return[id(e,b-e)];k=e;h=f;d=d-h+1;g=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(g),b[l][0]=l;for(l=0;l<g;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<g;m++)if(a[k+m-1]===c[h+l-1])b[l][m]=
b[l-1][m-1];else{var n=b[l-1][m]+1,t=b[l][m-1]+1;b[l][m]=n<t?n:t}k=b.length-1;h=b[0].length-1;d=b[k][h];for(a=[];0<k||0<h;)0==k?(a.push(2),h--):0==h?(a.push(3),k--):(g=b[k-1][h-1],l=b[k-1][h],m=b[k][h-1],n=l<m?l<g?l:g:m<g?m:g,n==g?(g==d?a.push(0):(a.push(1),d=g),k--,h--):n==l?(a.push(3),k--,d=l):(a.push(2),h--,d=m));a.reverse();b=void 0;k=[];for(h=0;h<a.length;h++)switch(a[h]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=id(e,0));b.T++;e++;b.N.push(c[f]);f++;break;case 2:b||(b=id(e,0));
b.T++;e++;break;case 3:b||(b=id(e,0)),b.N.push(c[f]),f++}b&&k.push(b);return k}function kd(a,b){return a===b};var ld={};function H(a,b,c){if(a!==ld)throw new TypeError("Illegal constructor");a=document.createDocumentFragment();a.__proto__=H.prototype;a.ya="ShadyRoot";yc(b);yc(a);a.host=b;a.Fa=c&&c.mode;b.__shady=b.__shady||{};b.__shady.root=a;b.__shady.Wa="closed"!==a.Fa?a:null;a.S=!1;a.o=[];a.l={};a.G=[];c=C.childNodes(b);for(var d=0,e=c.length;d<e;d++)A.removeChild.call(b,c[d]);return a}H.prototype=Object.create(DocumentFragment.prototype);function Bc(a){a.S||(a.S=!0,Lb(function(){return md(a)}))}
function md(a){for(var b;a;){a.S&&(b=a);a:{var c=a;a=c.host.getRootNode();if(z(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
H.prototype._renderRoot=function(){this.S=!1;Gc(this);for(var a=0,b;a<this.o.length;a++){b=this.o[a];var c=b.__shady.assignedNodes;b.__shady.assignedNodes=[];b.__shady.J=[];if(b.__shady.oa=c)for(var d=0;d<c.length;d++){var e=c[d];e.__shady.ga=e.__shady.assignedSlot;e.__shady.assignedSlot===b&&(e.__shady.assignedSlot=null)}}for(b=this.host.firstChild;b;b=b.nextSibling)nd(this,b);for(a=0;a<this.o.length;a++){b=this.o[a];if(!b.__shady.assignedNodes.length)for(c=b.firstChild;c;c=c.nextSibling)nd(this,
c,b);c=b.parentNode;(c=c.__shady&&c.__shady.root)&&Hc(c)&&c._renderRoot();od(this,b.__shady.J,b.__shady.assignedNodes);if(c=b.__shady.oa){for(d=0;d<c.length;d++)c[d].__shady.ga=null;b.__shady.oa=null;c.length>b.__shady.assignedNodes.length&&(b.__shady.ia=!0)}b.__shady.ia&&(b.__shady.ia=!1,pd(this,b))}a=this.o;b=[];for(c=0;c<a.length;c++)d=a[c].parentNode,d.__shady&&d.__shady.root||!(0>b.indexOf(d))||b.push(d);for(a=0;a<b.length;a++){c=b[a];d=c===this?this.host:c;e=[];c=c.childNodes;for(var f=0;f<
c.length;f++){var h=c[f];if("slot"==h.localName){h=h.__shady.J;for(var g=0;g<h.length;g++)e.push(h[g])}else e.push(h)}c=void 0;f=C.childNodes(d);h=jd(e,e.length,f,f.length);for(var k=g=0;g<h.length&&(c=h[g]);g++){for(var l=0,m;l<c.N.length&&(m=c.N[l]);l++)C.parentNode(m)===d&&A.removeChild.call(d,m),f.splice(c.index+k,1);k-=c.T}for(k=0;k<h.length&&(c=h[k]);k++)for(g=f[c.index],l=c.index;l<c.index+c.T;l++)m=e[l],A.insertBefore.call(d,m,g),f.splice(l,0,m)}};
function nd(a,b,c){b.__shady=b.__shady||{};var d=b.__shady.ga;b.__shady.ga=null;c||(c=(a=a.l[b.slot||"__catchall"])&&a[0]);c?(c.__shady.assignedNodes.push(b),b.__shady.assignedSlot=c):b.__shady.assignedSlot=void 0;d!==b.__shady.assignedSlot&&b.__shady.assignedSlot&&(b.__shady.assignedSlot.__shady.ia=!0)}function od(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=e.__shady.assignedNodes;f&&f.length&&od(a,b,f)}else b.push(c[d])}
function pd(a,b){A.dispatchEvent.call(b,new Event("slotchange"));b.__shady.assignedSlot&&pd(a,b.__shady.assignedSlot)}function Gc(a){if(a.G.length){for(var b=a.G,c,d=0;d<b.length;d++){var e=b[d];e.__shady=e.__shady||{};yc(e);yc(e.parentNode);var f=Jc(e);a.l[f]?(c=c||{},c[f]=!0,a.l[f].push(e)):a.l[f]=[e];a.o.push(e)}if(c)for(var h in c)a.l[h]=Kc(a.l[h]);a.G=[]}}function Jc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.Aa=b}
function Kc(a){return a.sort(function(a,c){a=qd(a);for(var b=qd(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}function qd(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}function Hc(a){Gc(a);return!!a.o.length}H.prototype.addEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.aa=this;this.host.addEventListener(a,b,c)};
H.prototype.removeEventListener=function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.aa=this;this.host.removeEventListener(a,b,c)};H.prototype.getElementById=function(a){return Mc(this,function(b){return b.id==a},function(a){return!!a})[0]||null};var rd=H.prototype;F(rd,sc,!0);F(rd,uc,!0);function sd(a){var b=a.getRootNode();z(b)&&md(b);return a.__shady&&a.__shady.assignedSlot||null}
var td={addEventListener:bd.bind(window),removeEventListener:dd.bind(window)},ud={addEventListener:bd,removeEventListener:dd,appendChild:function(a){return zc(this,a)},insertBefore:function(a,b){return zc(this,a,b)},removeChild:function(a){return Ac(this,a)},replaceChild:function(a,b){zc(this,a,b);Ac(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=A.cloneNode.call(this,a);else if(b=A.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Lc(this)},contains:function(a){return Ib(this,a)},get isConnected(){var a=this.ownerDocument;if(Hb&&A.contains.call(a,this)||a.documentElement&&A.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(a instanceof H?a.host:void 0);return!!(a&&a instanceof Document)},dispatchEvent:function(a){Mb();return A.dispatchEvent.call(this,a)}},vd={get assignedSlot(){return sd(this)}},
wd={querySelector:function(a){return Mc(this,function(b){return zb.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a){return Mc(this,function(b){return zb.call(b,a)})}},xd={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();z(b)&&md(b);return this.__shady?(a&&a.flatten?this.__shady.J:this.__shady.assignedNodes)||[]:[]}}},yd=Bb({setAttribute:function(a,b){Pc(this,a,b)},removeAttribute:function(a){A.removeAttribute.call(this,a);Ic(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";
if(!a)throw"Not enough arguments.";return new H(ld,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Pc(this,"slot",a)},get assignedSlot(){return sd(this)}},wd,xd);Object.defineProperties(yd,tc);var zd=Bb({importNode:function(a,b){return Qc(a,b)},getElementById:function(a){return Mc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},wd);Object.defineProperties(zd,{_activeElement:uc.activeElement});
var Ad=HTMLElement.prototype.blur,Bd=Bb({blur:function(){var a=this.__shady&&this.__shady.root;(a=a&&a.activeElement)?a.blur():Ad.call(this)}});function I(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(x.sa){var ShadyDOM={inUse:x.sa,patch:function(a){return a},isShadyRoot:z,enqueue:Lb,flush:Mb,settings:x,filterMutations:Sb,observeChildren:Qb,unobserveChildren:Rb,nativeMethods:A,nativeTree:C};window.ShadyDOM=ShadyDOM;window.Event=fd;window.CustomEvent=gd;window.MouseEvent=hd;ed();var Cd=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;I(window.Node.prototype,ud);I(window.Window.prototype,td);I(window.Text.prototype,vd);I(window.DocumentFragment.prototype,wd);I(window.Element.prototype,
yd);I(window.Document.prototype,zd);window.HTMLSlotElement&&I(window.HTMLSlotElement.prototype,xd);I(Cd.prototype,Bd);x.L&&(G(window.Node.prototype),G(window.Text.prototype),G(window.DocumentFragment.prototype),G(window.Element.prototype),G(Cd.prototype),G(window.Document.prototype),window.HTMLSlotElement&&G(window.HTMLSlotElement.prototype));window.ShadowRoot=H};var Dd=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function Ed(a){var b=Dd.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function K(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function Fd(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function L(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)L(d,b,c);d=Fd(a,e);continue}else if("template"===f){d=Fd(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)L(e,b,c)}d=d.firstChild?d.firstChild:Fd(a,d)}}function M(a,b,c){a[b]=c};function Gd(){this.a=new Map;this.s=new Map;this.h=[];this.c=!1}function Hd(a,b,c){a.a.set(b,c);a.s.set(c.constructor,c)}function Id(a,b){a.c=!0;a.h.push(b)}function Jd(a,b){a.c&&L(b,function(b){return a.b(b)})}Gd.prototype.b=function(a){if(this.c&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.h.length;b++)this.h[b](a)}};function N(a,b){var c=[];L(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):Kd(a,d)}}
function O(a,b){var c=[];L(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function P(a,b,c){c=void 0===c?{}:c;var d=c.ab||new Set,e=c.Y||function(b){return Kd(a,b)},f=[];L(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var c=b.import;c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:b.addEventListener("load",function(){var c=b.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f.delete(c);P(a,c,{ab:f,Y:e})}})}else f.push(b)},d);if(a.c)for(b=
0;b<f.length;b++)a.b(f[b]);for(b=0;b<f.length;b++)e(f[b])}
function Kd(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.a.get(b.localName)){c.constructionStack.push(b);var d=c.constructor;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(h){throw b.__CE_state=2,h;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=c[d],
f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}K(b)&&a.connectedCallback(b)}}}Gd.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};Gd.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
Gd.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function Ld(a){var b=document;this.i=a;this.a=b;this.C=void 0;P(this.i,this.a);"loading"===this.a.readyState&&(this.C=new MutationObserver(this.b.bind(this)),this.C.observe(this.a,{childList:!0,subtree:!0}))}Ld.prototype.disconnect=function(){this.C&&this.C.disconnect()};Ld.prototype.b=function(a){var b=this.a.readyState;"interactive"!==b&&"complete"!==b||this.disconnect();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)P(this.i,c[d])};function Md(){var a=this;this.b=this.a=void 0;this.c=new Promise(function(b){a.b=b;a.a&&b(a.a)})}Md.prototype.resolve=function(a){if(this.a)throw Error("Already resolved.");this.a=a;this.b&&this.b(a)};function Q(a){this.da=!1;this.i=a;this.ha=new Map;this.ea=function(a){return a()};this.P=!1;this.fa=[];this.Da=new Ld(a)}p=Q.prototype;
p.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!Ed(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.i.a.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.da)throw Error("A custom element is already being defined.");this.da=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var h=d("disconnectedCallback");var g=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(m){return}finally{this.da=!1}b={localName:a,constructor:b,connectedCallback:f,disconnectedCallback:h,adoptedCallback:g,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};Hd(this.i,a,b);this.fa.push(b);
this.P||(this.P=!0,this.ea(function(){return Nd(c)}))};p.Y=function(a){P(this.i,a)};function Nd(a){if(!1!==a.P){a.P=!1;for(var b=a.fa,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);P(a.i,document,{Y:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.i.a.get(e)&&c.push(b)}}});for(e=0;e<c.length;e++)Kd(a.i,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var h=0;h<f.length;h++)Kd(a.i,f[h]);(e=a.ha.get(e))&&e.resolve(void 0)}}}
p.get=function(a){if(a=this.i.a.get(a))return a.constructor};p.va=function(a){if(!Ed(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.ha.get(a);if(b)return b.c;b=new Md;this.ha.set(a,b);this.i.a.get(a)&&!this.fa.some(function(b){return b.localName===a})&&b.resolve(void 0);return b.c};p.Va=function(a){this.Da.disconnect();var b=this.ea;this.ea=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=Q;Q.prototype.define=Q.prototype.define;
Q.prototype.upgrade=Q.prototype.Y;Q.prototype.get=Q.prototype.get;Q.prototype.whenDefined=Q.prototype.va;Q.prototype.polyfillWrapFlushCallback=Q.prototype.Va;var Od=window.Document.prototype.createElement,Pd=window.Document.prototype.createElementNS,Qd=window.Document.prototype.importNode,Rd=window.Document.prototype.prepend,Sd=window.Document.prototype.append,Td=window.DocumentFragment.prototype.prepend,Ud=window.DocumentFragment.prototype.append,Vd=window.Node.prototype.cloneNode,Wd=window.Node.prototype.appendChild,Xd=window.Node.prototype.insertBefore,Yd=window.Node.prototype.removeChild,Zd=window.Node.prototype.replaceChild,$d=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),ae=window.Element.prototype.attachShadow,be=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),ce=window.Element.prototype.getAttribute,de=window.Element.prototype.setAttribute,ee=window.Element.prototype.removeAttribute,fe=window.Element.prototype.getAttributeNS,ge=window.Element.prototype.setAttributeNS,he=window.Element.prototype.removeAttributeNS,ie=window.Element.prototype.insertAdjacentElement,je=window.Element.prototype.insertAdjacentHTML,ke=window.Element.prototype.prepend,
le=window.Element.prototype.append,me=window.Element.prototype.before,ne=window.Element.prototype.after,oe=window.Element.prototype.replaceWith,pe=window.Element.prototype.remove,qe=window.HTMLElement,re=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),se=window.HTMLElement.prototype.insertAdjacentElement,te=window.HTMLElement.prototype.insertAdjacentHTML;var ue=new function(){};function ve(){var a=we;window.HTMLElement=function(){function b(){var b=this.constructor,d=a.s.get(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=Od.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.b(e),e;d=e.length-1;var f=e[d];if(f===ue)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=ue;Object.setPrototypeOf(f,b.prototype);a.b(f);return f}b.prototype=qe.prototype;return b}()};function xe(a,b,c){function d(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var f=[],l=0;l<d.length;l++){var m=d[l];m instanceof Element&&K(m)&&f.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)e.push(m);else e.push(m)}b.apply(this,d);for(d=0;d<f.length;d++)O(a,f[d]);if(K(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&N(a,f)}}void 0!==c.W&&(b.prepend=d(c.W));void 0!==c.append&&(b.append=d(c.append))};function ye(){var a=we;M(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.a.get(b);if(c)return new c.constructor}b=Od.call(this,b);a.b(b);return b});M(Document.prototype,"importNode",function(b,c){b=Qd.call(this,b,c);this.__CE_hasRegistry?P(a,b):Jd(a,b);return b});M(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.a.get(c);if(d)return new d.constructor}b=Pd.call(this,b,c);a.b(b);return b});
xe(a,Document.prototype,{W:Rd,append:Sd})};function ze(){var a=we;function b(b,d){Object.defineProperty(b,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(b){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,b);else{var c=void 0;if(this.firstChild){var e=this.childNodes,g=e.length;if(0<g&&K(this)){c=Array(g);for(var k=0;k<g;k++)c[k]=e[k]}}d.set.call(this,b);if(c)for(b=0;b<c.length;b++)O(a,c[b])}}})}M(Node.prototype,"insertBefore",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);
b=Xd.call(this,b,d);if(K(this))for(d=0;d<c.length;d++)N(a,c[d]);return b}c=K(b);d=Xd.call(this,b,d);c&&O(a,b);K(this)&&N(a,b);return d});M(Node.prototype,"appendChild",function(b){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Wd.call(this,b);if(K(this))for(var e=0;e<c.length;e++)N(a,c[e]);return b}c=K(b);e=Wd.call(this,b);c&&O(a,b);K(this)&&N(a,b);return e});M(Node.prototype,"cloneNode",function(b){b=Vd.call(this,b);this.ownerDocument.__CE_hasRegistry?P(a,b):
Jd(a,b);return b});M(Node.prototype,"removeChild",function(b){var c=K(b),e=Yd.call(this,b);c&&O(a,b);return e});M(Node.prototype,"replaceChild",function(b,d){if(b instanceof DocumentFragment){var c=Array.prototype.slice.apply(b.childNodes);b=Zd.call(this,b,d);if(K(this))for(O(a,d),d=0;d<c.length;d++)N(a,c[d]);return b}c=K(b);var f=Zd.call(this,b,d),h=K(this);h&&O(a,d);c&&O(a,b);h&&N(a,b);return f});$d&&$d.get?b(Node.prototype,$d):Id(a,function(a){b(a,{enumerable:!0,configurable:!0,get:function(){for(var a=
[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)Yd.call(this,this.firstChild);Wd.call(this,document.createTextNode(a))}})})};function Ae(a){var b=Element.prototype;function c(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var g=[],k=0;k<d.length;k++){var l=d[k];l instanceof Element&&K(l)&&g.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)e.push(l);else e.push(l)}b.apply(this,d);for(d=0;d<g.length;d++)O(a,g[d]);if(K(this))for(d=0;d<e.length;d++)g=e[d],g instanceof Element&&N(a,g)}}void 0!==me&&(b.before=c(me));void 0!==me&&(b.after=c(ne));void 0!==
oe&&M(b,"replaceWith",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];d=[];for(var h=[],g=0;g<c.length;g++){var k=c[g];k instanceof Element&&K(k)&&h.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)d.push(k);else d.push(k)}g=K(this);oe.apply(this,c);for(c=0;c<h.length;c++)O(a,h[c]);if(g)for(O(a,this),c=0;c<d.length;c++)h=d[c],h instanceof Element&&N(a,h)});void 0!==pe&&M(b,"remove",function(){var b=K(this);pe.call(this);b&&O(a,this)})};function Be(){var a=we;function b(b,c){Object.defineProperty(b,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(b){var d=this,e=void 0;K(this)&&(e=[],L(this,function(a){a!==d&&e.push(a)}));c.set.call(this,b);if(e)for(var f=0;f<e.length;f++){var h=e[f];1===h.__CE_state&&a.disconnectedCallback(h)}this.ownerDocument.__CE_hasRegistry?P(a,this):Jd(a,this);return b}})}function c(b,c){M(b,"insertAdjacentElement",function(b,d){var e=K(d);b=c.call(this,b,d);e&&O(a,d);K(b)&&N(a,d);
return b})}function d(b,c){function d(b,c){for(var d=[];b!==c;b=b.nextSibling)d.push(b);for(c=0;c<d.length;c++)P(a,d[c])}M(b,"insertAdjacentHTML",function(a,b){a=a.toLowerCase();if("beforebegin"===a){var e=this.previousSibling;c.call(this,a,b);d(e||this.parentNode.firstChild,this)}else if("afterbegin"===a)e=this.firstChild,c.call(this,a,b),d(this.firstChild,e);else if("beforeend"===a)e=this.lastChild,c.call(this,a,b),d(e||this.firstChild,null);else if("afterend"===a)e=this.nextSibling,c.call(this,
a,b),d(this.nextSibling,e);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}ae&&M(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=ae.call(this,a)});be&&be.get?b(Element.prototype,be):re&&re.get?b(HTMLElement.prototype,re):Id(a,function(a){b(a,{enumerable:!0,configurable:!0,get:function(){return Vd.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:
this,d=Od.call(document,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)Yd.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)Wd.call(c,a.childNodes[0])}})});M(Element.prototype,"setAttribute",function(b,c){if(1!==this.__CE_state)return de.call(this,b,c);var d=ce.call(this,b);de.call(this,b,c);c=ce.call(this,b);a.attributeChangedCallback(this,b,d,c,null)});M(Element.prototype,"setAttributeNS",function(b,c,d){if(1!==this.__CE_state)return ge.call(this,b,c,d);var e=fe.call(this,
b,c);ge.call(this,b,c,d);d=fe.call(this,b,c);a.attributeChangedCallback(this,c,e,d,b)});M(Element.prototype,"removeAttribute",function(b){if(1!==this.__CE_state)return ee.call(this,b);var c=ce.call(this,b);ee.call(this,b);null!==c&&a.attributeChangedCallback(this,b,c,null,null)});M(Element.prototype,"removeAttributeNS",function(b,c){if(1!==this.__CE_state)return he.call(this,b,c);var d=fe.call(this,b,c);he.call(this,b,c);var e=fe.call(this,b,c);d!==e&&a.attributeChangedCallback(this,c,d,e,b)});se?
c(HTMLElement.prototype,se):ie?c(Element.prototype,ie):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");te?d(HTMLElement.prototype,te):je?d(Element.prototype,je):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");xe(a,Element.prototype,{W:ke,append:le});Ae(a)};var Ce=window.customElements;if(!Ce||Ce.forcePolyfill||"function"!=typeof Ce.define||"function"!=typeof Ce.get){var we=new Gd;ve();ye();xe(we,DocumentFragment.prototype,{W:Td,append:Ud});ze();Be();document.__CE_hasRegistry=!0;var customElements=new Q(we);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};function De(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Ee(a){a=a.replace(Fe,"").replace(Ge,"");var b=Je,c=a,d=new De;d.start=0;d.end=c.length;for(var e=d,f=0,h=c.length;f<h;f++)if("{"===c[f]){e.rules||(e.rules=[]);var g=e,k=g.rules[g.rules.length-1]||null;e=new De;e.start=f+1;e.parent=g;e.previous=k;g.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function Je(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Ke(c),c=c.replace(Le," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=Me:c.match(Ne)&&(a.type=Oe,a.keyframesName=a.selector.split(Le).pop()):a.type=0===c.indexOf("--")?Pe:Qe);if(c=a.rules)for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)Je(f,
b);return a}function Ke(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function Re(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var h=e.length,g;f<h&&(g=e[f]);f++)d=Re(g,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(Se,"").replace(Te,""),b=b.replace(Ue,"").replace(Ve,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var Qe=1,Oe=7,Me=4,Pe=1E3,Fe=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Ge=/@import[^;]*;/gim,Se=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Te=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Ue=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Ve=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Ne=/^@[^\s]*keyframes/,Le=/\s+/g;var R=!(window.ShadyDOM&&window.ShadyDOM.inUse),We;function Xe(a){We=a&&a.shimcssproperties?!1:R||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?We=window.ShadyCSS.nativeCss:window.ShadyCSS?(Xe(window.ShadyCSS),window.ShadyCSS=void 0):Xe(window.WebComponents&&window.WebComponents.flags);var S=We;var Ye=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,Ze=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,$e=/(--[\w-]+)\s*([:,;)]|$)/gi,af=/(animation\s*:)|(animation-name\s*:)/,bf=/@media\s(.*)/,cf=/\{[^}]*\}/g;var df=new Set;function ef(a,b){if(!a)return"";"string"===typeof a&&(a=Ee(a));b&&ff(a,b);return Re(a,S)}function gf(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Ee(a.textContent));return a.__cssRules||null}function hf(a){return!!a.parent&&a.parent.type===Oe}function ff(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===Me){var h=a.selector.match(bf);h&&(window.matchMedia(h[1]).matches||(e=!0))}f===Qe?b(a):c&&f===Oe?c(a):f===Pe&&(e=!0);if((a=a.rules)&&!e){e=0;f=a.length;for(var g;e<f&&(g=a[e]);e++)ff(g,b,c,d)}}}
function jf(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;kf(e,c,d);return e}var lf=null;function kf(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);lf?a.compareDocumentPosition(lf)===Node.DOCUMENT_POSITION_PRECEDING&&(lf=a):lf=a}
function mf(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");a:{var d=0;var e=c+3;for(var f=a.length;e<f;e++)if("("===a[e])d++;else if(")"===a[e]&&0===--d)break a;e=-1}d=a.substring(c+4,e);c=a.substring(0,c);a=mf(a.substring(e+1),b);e=d.indexOf(",");return-1===e?b(c,d.trim(),"",a):b(c,d.substring(0,e).trim(),d.substring(e+1).trim(),a)}function nf(a,b){R?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function T(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,O:c}};function of(){}function pf(a,b,c){var d=U;a.__styleScoped?a.__styleScoped=null:qf(d,a,b||"",c)}function qf(a,b,c,d){b.nodeType===Node.ELEMENT_NODE&&rf(b,c,d);if(b="template"===b.localName?(b.content||b.hb).childNodes:b.children||b.childNodes)for(var e=0;e<b.length;e++)qf(a,b[e],c,d)}
function rf(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute(sf);c?d&&(b=d.replace("style-scope","").replace(b,""),nf(a,b)):nf(a,(d?d+" ":"")+"style-scope "+b)}}function tf(a,b,c){var d=U,e=a.__cssBuild;R||"shady"===e?b=ef(b,c):(a=T(a),b=uf(d,b,a.is,a.O,c)+"\n\n");return b.trim()}
function uf(a,b,c,d,e){var f=vf(c,d);c=c?wf+c:"";return ef(b,function(b){b.c||(b.selector=b.m=xf(a,b,a.b,c,f),b.c=!0);e&&e(b,c,f)})}function vf(a,b){return b?"[is="+a+"]":a}function xf(a,b,c,d,e){var f=b.selector.split(yf);if(!hf(b)){b=0;for(var h=f.length,g;b<h&&(g=f[b]);b++)f[b]=c.call(a,g,d,e)}return f.join(yf)}function zf(a){return a.replace(Af,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
of.prototype.b=function(a,b,c){var d=!1;a=a.trim();var e=Af.test(a);e&&(a=a.replace(Af,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=zf(a));a=a.replace(Bf,Cf+" $1");a=a.replace(Df,function(a,e,g){d||(a=Ef(g,e,b,c),d=d||a.stop,e=a.Ka,g=a.value);return e+g});e&&(a=zf(a));return a};
function Ef(a,b,c,d){var e=a.indexOf(Ff);0<=a.indexOf(Cf)?a=Gf(a,d):0!==e&&(a=c?Hf(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(If,function(a,b){return" > "+b}))}a=a.replace(Jf,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,Ka:b,stop:f}}function Hf(a,b){a=a.split(Kf);a[0]+=b;return a.join(Kf)}
function Gf(a,b){var c=a.match(Lf);return(c=c&&c[2].trim()||"")?c[0].match(Mf)?a.replace(Lf,function(a,c,f){return b+f}):c.split(Mf)[0]===b?c:Nf:a.replace(Cf,b)}function Of(a){a.selector===Pf&&(a.selector="html")}of.prototype.c=function(a){return a.match(Ff)?this.b(a,Qf):Hf(a.trim(),Qf)};q.Object.defineProperties(of.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Af=/:(nth[-\w]+)\(([^)]+)\)/,Qf=":not(.style-scope)",yf=",",Df=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Mf=/[[.:#*]/,Cf=":host",Pf=":root",Ff="::slotted",Bf=new RegExp("^("+Ff+")"),Lf=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,If=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Jf=/(.*):dir\((?:(ltr|rtl))\)/,wf=".",Kf=":",sf="class",Nf="should_not_match",U=new of;function Rf(a,b,c,d){this.w=a||null;this.b=b||null;this.ja=c||[];this.F=null;this.O=d||"";this.a=this.u=this.B=null}function V(a){return a?a.__styleInfo:null}function Sf(a,b){return a.__styleInfo=b}Rf.prototype.c=function(){return this.w};Rf.prototype._getStyleRules=Rf.prototype.c;function Tf(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Uf=navigator.userAgent.match("Trident");function Vf(){}function Wf(a){var b={},c=[],d=0;ff(a,function(a){Xf(a);a.index=d++;a=a.j.cssText;for(var c;c=$e.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.b=c;a=[];for(var e in b)a.push(e);return a}
function Xf(a){if(!a.j){var b={},c={};Yf(a,c)&&(b.v=c,a.rules=null);b.cssText=a.parsedCssText.replace(cf,"").replace(Ye,"");a.j=b}}function Yf(a,b){var c=a.j;if(c){if(c.v)return Object.assign(b,c.v),!0}else{c=a.parsedCssText;for(var d;a=Ye.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function Zf(a,b,c){b&&(b=0<=b.indexOf(";")?$f(a,b,c):mf(b,function(b,e,f,h){if(!e)return b+h;(e=Zf(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=Zf(a,c[f]||f,c)||f;return b+(e||"")+h}));return b&&b.trim()||""}
function $f(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){Ze.lastIndex=0;if(f=Ze.exec(e))e=Zf(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var h=e.substring(f);h=h.trim();h=Zf(a,h,c)||h;e=e.substring(0,f)+h}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function ag(a,b){var c={},d=[];ff(a,function(a){a.j||Xf(a);var e=a.m||a.parsedSelector;b&&a.j.v&&e&&Tf.call(b,e)&&(Yf(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{v:c,key:d}}
function bg(a,b,c,d){b.j||Xf(b);if(b.j.v){var e=T(a);a=e.is;e=e.O;e=a?vf(a,e):"html";var f=b.parsedSelector,h=":host > *"===f||"html"===f,g=0===f.indexOf(":host")&&!h;"shady"===c&&(h=f===e+" > *."+e||-1!==f.indexOf("html"),g=!h&&0===f.indexOf(e));"shadow"===c&&(h=":host > *"===f||"html"===f,g=g&&!h);if(h||g)c=e,g&&(b.m||(b.m=xf(U,b,U.b,a?wf+a:"",e)),c=b.m||e),d({Ya:c,Qa:g,ib:h})}}
function cg(a,b){var c={},d={},e=b&&b.__cssBuild;ff(b,function(b){bg(a,b,e,function(e){Tf.call(a.b||a,e.Ya)&&(e.Qa?Yf(b,c):Yf(b,d))})},null,!0);return{Xa:d,Oa:c}}
function dg(a,b,c,d){var e=T(b),f=vf(e.is,e.O),h=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])");e=V(b).w;var g=eg(e,d);return tf(b,e,function(b){var e="";b.j||Xf(b);b.j.cssText&&(e=$f(a,b.j.cssText,c));b.cssText=e;if(!R&&!hf(b)&&b.cssText){var k=e=b.cssText;null==b.ra&&(b.ra=af.test(e));if(b.ra)if(null==b.V){b.V=[];for(var n in g)k=g[n],k=k(e),e!==k&&(e=k,b.V.push(n))}else{for(n=0;n<b.V.length;++n)k=g[b.V[n]],e=k(e);k=e}b.cssText=k;b.m=b.m||b.selector;e="."+d;
n=b.m.split(",");k=0;for(var t=n.length,B;k<t&&(B=n[k]);k++)n[k]=B.match(h)?B.replace(f,e):e+" "+B;b.selector=n.join(",")}})}function eg(a,b){a=a.b;var c={};if(!R&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,h=b;f.h=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.a=f.keyframesName+"-"+h;f.m=f.m||f.selector;f.selector=f.m.replace(f.keyframesName,f.a);c[e.keyframesName]=fg(e)}return c}function fg(a){return function(b){return b.replace(a.h,a.a)}}
function gg(a,b){var c=hg,d=gf(a);a.textContent=ef(d,function(a){var d=a.cssText=a.parsedCssText;a.j&&a.j.cssText&&(d=d.replace(Se,"").replace(Te,""),a.cssText=$f(c,d,b))})}q.Object.defineProperties(Vf.prototype,{a:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var hg=new Vf;var ig={},jg=window.customElements;if(jg&&!R){var kg=jg.define;jg.define=function(a,b,c){var d=document.createComment(" Shady DOM styles for "+a+" "),e=document.head;e.insertBefore(d,(lf?lf.nextSibling:null)||e.firstChild);lf=d;ig[a]=d;kg.call(jg,a,b,c)}};function lg(){this.cache={}}lg.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({v:b,styleElement:c,u:d});100<e.length&&e.shift();this.cache[a]=e};lg.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d],f;a:{for(f=0;f<c.length;f++){var h=c[f];if(e.v[h]!==b[h]){f=!1;break a}}f=!0}if(f)return e}};function mg(){}
function ng(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode();var h=e;var g=[];h.classList?g=Array.from(h.classList):h instanceof window.SVGElement&&h.hasAttribute("class")&&(g=h.getAttribute("class").split(/\s+/));h=g;g=h.indexOf(U.a);if((h=-1<g?h[g+1]:"")&&f===e.ownerDocument)pf(e,h,!0);else if(f.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&
(f=f.host)){f=T(f).is;g=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+U.a+")");for(var k=0;k<g.length;k++){var l=g[k],m=l.getRootNode().host;m&&(m=T(m).is,rf(l,m))}f!==h&&(h&&pf(e,h,!0),pf(e,f))}}}}}
if(!R){var og=new MutationObserver(ng),pg=function(a){og.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)pg(document);else{var qg=function(){pg(document.body)};window.HTMLImports?window.HTMLImports.whenReady(qg):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){qg();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",a)}else qg()})}mg=function(){ng(og.takeRecords())}}
var rg=mg;var sg={};var tg=Promise.resolve();function ug(a){if(a=sg[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function vg(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function wg(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a.qa||(a.qa=!0,tg.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a.qa=!1}))};var xg=new lg;function Y(){this.K={};this.c=document.documentElement;var a=new De;a.rules=[];this.h=Sf(this.c,new Rf(a));this.s=!1;this.b=this.a=null}p=Y.prototype;p.wa=function(){rg()};p.Ma=function(a){return gf(a)};p.$a=function(a){return ef(a)};
p.prepareTemplate=function(a,b,c){if(!a.Ia){a.Ia=!0;a.name=b;a.extends=c;sg[b]=a;var d=(d=a.content.querySelector("style"))?d.getAttribute("css-build")||"":"";var e=[];for(var f=a.content.querySelectorAll("style"),h=0;h<f.length;h++){var g=f[h];if(g.hasAttribute("shady-unscoped")){if(!R){var k=g.textContent;df.has(k)||(df.add(k),k=g.cloneNode(!0),document.head.appendChild(k));g.parentNode.removeChild(g)}}else e.push(g.textContent),g.parentNode.removeChild(g)}e=e.join("").trim();c={is:b,extends:c,
fb:d};R||pf(a.content,b);yg(this);f=Ze.test(e)||Ye.test(e);Ze.lastIndex=0;Ye.lastIndex=0;e=Ee(e);f&&S&&this.a&&this.a.transformRules(e,b);a._styleAst=e;a.a=d;d=[];S||(d=Wf(a._styleAst));if(!d.length||S)e=R?a.content:null,b=ig[b],f=tf(c,a._styleAst),b=f.length?jf(f,c.is,e,b):void 0,a.pa=b;a.Ha=d}};
function zg(a){!a.b&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.b=window.ShadyCSS.CustomStyleInterface,a.b.transformCallback=function(b){a.ua(b)},a.b.validateCallback=function(){requestAnimationFrame(function(){(a.b.enqueued||a.s)&&a.flushCustomStyles()})})}function yg(a){!a.a&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.a=window.ShadyCSS.ApplyShim,a.a.invalidCallback=ug);zg(a)}
p.flushCustomStyles=function(){yg(this);if(this.b){var a=this.b.processStyles();if(this.b.enqueued){if(S)for(var b=0;b<a.length;b++){var c=this.b.getStyleForCustomStyle(a[b]);if(c&&S&&this.a){var d=gf(c);yg(this);this.a.transformRules(d);c.textContent=ef(d)}}else for(Ag(this,this.c,this.h),b=0;b<a.length;b++)(c=this.b.getStyleForCustomStyle(a[b]))&&gg(c,this.h.B);this.b.enqueued=!1;this.s&&!S&&this.styleDocument()}}};
p.styleElement=function(a,b){var c=T(a).is,d=V(a);if(!d){var e=T(a);d=e.is;e=e.O;var f=ig[d];d=sg[d];if(d){var h=d._styleAst;var g=d.Ha}d=Sf(a,new Rf(h,f,g,e))}a!==this.c&&(this.s=!0);b&&(d.F=d.F||{},Object.assign(d.F,b));if(S){if(d.F){b=d.F;for(var k in b)null===k?a.style.removeProperty(k):a.style.setProperty(k,b[k])}if(((k=sg[c])||a===this.c)&&k&&k.pa&&!vg(k)){if(vg(k)||k._applyShimValidatingVersion!==k._applyShimNextVersion)yg(this),this.a&&this.a.transformRules(k._styleAst,c),k.pa.textContent=
tf(a,d.w),wg(k);R&&(c=a.shadowRoot)&&(c.querySelector("style").textContent=tf(a,d.w));d.w=k._styleAst}}else if(Ag(this,a,d),d.ja&&d.ja.length){c=d;k=T(a).is;d=(b=xg.fetch(k,c.B,c.ja))?b.styleElement:null;h=c.u;(g=b&&b.u)||(g=this.K[k]=(this.K[k]||0)+1,g=k+"-"+g);c.u=g;g=c.u;e=hg;e=d?d.textContent||"":dg(e,a,c.B,g);f=V(a);var l=f.a;l&&!R&&l!==d&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));R?f.a?(f.a.textContent=e,d=f.a):e&&(d=jf(e,g,a.shadowRoot,f.b)):d?d.parentNode||
(Uf&&-1<e.indexOf("@media")&&(d.textContent=e),kf(d,null,f.b)):e&&(d=jf(e,g,null,f.b));d&&(d._useCount=d._useCount||0,f.a!=d&&d._useCount++,f.a=d);g=d;R||(d=c.u,f=e=a.getAttribute("class")||"",h&&(f=e.replace(new RegExp("\\s*x-scope\\s*"+h+"\\s*","g")," ")),f+=(f?" ":"")+"x-scope "+d,e!==f&&nf(a,f));b||xg.store(k,c.B,g,c.u)}};function Bg(a,b){return(b=b.getRootNode().host)?V(b)?b:Bg(a,b):a.c}
function Ag(a,b,c){a=Bg(a,b);var d=V(a);a=Object.create(d.B||null);var e=cg(b,c.w);b=ag(d.w,b).v;Object.assign(a,e.Oa,b,e.Xa);b=c.F;for(var f in b)if((e=b[f])||0===e)a[f]=e;f=hg;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=Zf(f,a[d],a);c.B=a}p.styleDocument=function(a){this.styleSubtree(this.c,a)};
p.styleSubtree=function(a,b){var c=a.shadowRoot;(c||a===this.c)&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};p.ua=function(a){var b=this,c=gf(a);ff(c,function(a){if(R)Of(a);else{var c=U;a.selector=a.parsedSelector;Of(a);a.selector=a.m=xf(c,a,c.c,void 0,void 0)}S&&(yg(b),b.a&&b.a.transformRule(a))});S?a.textContent=ef(c):this.h.w.rules.push(c)};
p.getComputedStyleValue=function(a,b){var c;S||(c=(V(a)||V(Bg(this,a))).B[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};p.Za=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===U.a){c=d[e+1];break}}}c&&b.push(U.a,c);S||(c=V(a))&&c.u&&b.push(hg.a,c.u);nf(a,b.join(" "))};p.Ja=function(a){return V(a)};Y.prototype.flush=Y.prototype.wa;
Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Za;Y.prototype._styleInfoForNode=Y.prototype.Ja;Y.prototype.transformCustomStyleForDocument=Y.prototype.ua;Y.prototype.getStyleAst=Y.prototype.Ma;Y.prototype.styleAstToString=Y.prototype.$a;
Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return R}},nativeCss:{get:function(){return S}}});var Z=new Y,Cg,Dg;window.ShadyCSS&&(Cg=window.ShadyCSS.ApplyShim,Dg=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:S,nativeShadow:R};Cg&&(window.ShadyCSS.ApplyShim=Cg);
Dg&&(window.ShadyCSS.CustomStyleInterface=Dg);var Eg=window.customElements,Fg=window.HTMLImports,Gg=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(Eg&&Eg.polyfillWrapFlushCallback){var Hg,Ig=function(){if(Hg){Gg.I&&Gg.I(window.document);var a=Hg;Hg=null;a();return!0}},Jg=Fg.whenReady;Eg.polyfillWrapFlushCallback(function(a){Hg=a;Jg(Ig)});Fg.whenReady=function(a){Jg(function(){Ig()?Fg.whenReady(a):a()})}}
Fg.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var Kg=document.createElement("style");Kg.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var Lg=document.querySelector("head");Lg.insertBefore(Kg,Lg.firstChild);}).call(this);

//# sourceMappingURL=webcomponents-lite.js.map
